### ISSUE TITLE
Block Microsoft Bing Ads

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#1914] opened 2024-10-01 08:58 UTC
For example: https://www.bing.com/search?q=shoes&qs=n&form=QBRE&sp=-1&ghc=1&lq=0&pq=shoe&sc=10-4&sk=&cvid=C1008AABC10A417FA225E532149865BA&ghsh=0&ghacc=0&ghpl=

<img width="726" alt="Screenshot 2024-10-01 at 10 58 20" src="https://github.com/user-attachments/assets/f38535d5-e639-41c7-8ec3-b85a862f7b95">

**Comment by philipp-classen** [comment] 2024-10-01 09:00
Potential duplicate of https://github.com/ghostery/ghostery-extension/issues/1267

**Closed** 2024-10-01 09:03 UTC
Labels: Ad-Blocking
