### ISSUE TITLE
Google maps very slow when ghostery enabled. -> inform user about slow loading site?

### ISSUE THREAD

**Issue by Crare** [ghostery/ghostery-extension#330] opened 2019-01-27 08:08 UTC
### Description

While I run google maps pages, it gets very slow if I have ghostery enabled. I think this is because google maps keeps sending data constantly to multiple sources and ghostery is blocking it and google maps might be waiting for callback or something and it slows down. Problem gets fixed if I disable ghostery for google maps pages. My laptop starts warming up and fans start spinning loudly, this usually never happens when browsing web content or even watching videos 1080p or less.

This might be issue that may need to be fixed on google maps side. But I think the plugin could have some kinda notice that for example: "current page is taking long time to load, would you like to add it to the trusted sites so it loads faster. This might effect your privacy and so on.."
I think it would be wise to inform the user that it might be easier to view page without the plugin in some cases. Or have an option that disables just some of the content or some kinda profile filtering for this kinda of cases of websites.

### Expected Behavior 

Google maps pages to work fine. No fans spinning and no waiting long time to do any action.

### Actual Behavior 

Google maps getting slow, whole browser freezing up, taking long time to do any action. Waiting for zoom level to change or moving around the map. Laptop fans start spinning loudly, because laptop is warming up.

### Steps to Reproduce

1. have ghostery plugin installed and enabled on chrome on mac.
2. load google maps pages on chrome and trying to zoom and move around the raster/graphical map.
3. notice how slow it gets loading and freezing up the chrome browser.

### Versions

+ Browser: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
+ OS: MacOS Mojave 10.14.1 (18B75) on Macbook 13" 2018 model.
+ Node: v11.6.0
+ NPM: 6.5.0-next.0

**Comment by remusao** [comment] 2019-01-28 13:44
Hi @Crare!

Thank you for taking to time to report this issue. We've been investigating and this slow-down seems to be caused by some issue in the way the adblocker decides which cosmetic filters to inject in the page. To be more specific, when an action is performed in Google Maps (scrolling, moving around, etc.) the URL changes and this triggers a `location change` event which currently refreshes the cosmetics on the page (and this is a bit expensive). We will fix this ASAP.

**Comment by Achille-Grs** [comment] 2019-02-05 20:40
Hi! Just a small bug when I put the add-on Ghostery inside popup menu in Firefox 65!
Outside the popup menu like an extra button it's ok.
But... as you see the error pic inside popup menu, the bug is cutting the add-on popup box
(sorry for my poor english)
I hope the pics help the problem and fixed in the next update.
![9](https://user-images.githubusercontent.com/32937226/52302809-f8f2b680-2996-11e9-9baa-b9338f89da0e.png)

**Comment by christophertino** [comment] 2019-04-22 20:33
The issue with gmail and Google maps should be resolved in v8.3.2, which was released today.

**Closed** 2019-05-20 13:47 UTC
Labels: v8.3.2
