### ISSUE TITLE
How do I stop the Ghostery popup to show up?

### ISSUE THREAD

**Issue by rfalanga** [ghostery/ghostery-extension#500] opened 2020-02-25 01:52 UTC
### Description

Every time I open my browser The Ghostery popup window comes up, in the way. No matter how many times I, "Check out the sweet new features and defect fixes in this release" it _**never stops bothering me every time I open the browser!!!**_

### Expected Behavior 

I expect that once I've visited the link to check out the new features and defect fixes, that it will not pop up again.

### Actual Behavior 

That pop up comes up again and again and again and again and again and again and again ....

### Steps to Reproduce

1. Opening my browser, there is it in my face, always, every time

### Versions

+ Browser: Chromium version of MS Edge
+ OS: Windows 10 Professional
+ Node: (not sure)
+ NPM: (not sure)

**Comment by christophertino** [comment] 2020-03-02 14:47
Are you getting a new browser tab opening at launch or is it a little window in the top-right corner? Send over a screenshot if you can. 

If it's the latter, try going into Ghostery settings > Notifications > turn off the first four options.

**Comment by rfalanga** [comment] 2020-03-03 02:04
Its in the upper right corner. Its not what I would call small.

[cid:image001.png@01D5F0C5.681ECC10]

I was just searching, but it doesn’t matter if I search, or go to some link I’ve saved or one I’ve sent to myself, it is there, in the upper right all the time. I’ve really come to hate it and am an inch away from uninstalling the Ghostry add-in. What’s the point of an add-in that’s supposed to help reduce intrusions, etc., if it throws itself at me screaming

LOOK AT ME OR ELSE!!!!!


Rod

**Comment by christophertino** [comment] 2020-03-03 14:28
Yea that's definitely not intended behavior. Our next release (v8.4.7) cleans things up for the new Chromium Edge (#492).  Can you try turning off notifications as I mentioned previously (Ghostery settings > Notifications > turn off the first four options) to see if that helps temporarily?

**Comment by christophertino** [comment] 2020-03-18 14:34
Our Edge release was approved today. Could you update and let me know if this resolves the issue?

**Comment by rfalanga** [comment] 2020-03-19 00:31
How do I update the Edge release? I thought that might happen automatically, but if I'm wrong I'd be happy to give it a try.

**Comment by christophertino** [comment] 2020-03-27 16:26
If you go to edge://extensions, then at the bottom left turn on Developer Mode. On the top-right you should now see an Update icon.  Ghostery should be at v8.4.7.

**Comment by rfalanga** [comment] 2020-03-28 00:24
Thank you, @christophertino for your response. I didn't know about being able to go into Developer Mode. Thanks for that! After going into Developer Mode I discovered that I am running Ghostery v8.4.7

**Comment by christophertino** [comment] 2020-04-01 13:40
Glad you were able to get the update. Did it fix the pop-up issue?

**Comment by rfalanga** [comment] 2020-04-02 02:05
No.

**Comment by christophertino** [comment] 2020-04-14 14:17
In the popup window, what text are you seeing displayed?

**Comment by rfalanga** [comment] 2020-04-14 22:58
![Annotation 2020-04-14 165634](https://user-images.githubusercontent.com/11872620/79281936-16f85880-7e71-11ea-9fe5-d66ec5513c4c.png)

**Comment by BennoG** [comment] 2020-05-13 09:19
version 8.5.0 same popup as above every time I start chrome.
![image](https://user-images.githubusercontent.com/12594062/81794312-e4db2480-950a-11ea-930d-3e2938f4af66.png)

Also clear the settings with arrows (that should prevent this) are not saved after close and reopen chrome.

**Comment by BennoG** [comment] 2020-05-18 14:32
For some reason the popup stopped after a couple of day's  still at version 8.5.0 so there was no update involved.

**Comment by philipp-classen** [comment] 2022-01-26 19:26
We recently got similar bug reports: notifications about a release showing up (both within the same browsing session and across browser restarts).

I'm looking into it, but cannot reproduce so far. If someone runs into the problem and knows how to use the dev console (`about:debugging` or `chrome://extensions`), this output here could help us to narrow it down:

```
chrome.storage.local.get('version_history', x => console.log(JSON.stringify(x.version_history)))
chrome.storage.local.get('previous_version', x => console.log(x.previous_version))
```

For example, on my profile, my Ghostery version is 8.5.7 (on Firefox) and the output would be:
```
chrome.storage.local.get('version_history', x => console.log(JSON.stringify(x.version_history)))
->
["7.4.1.4","7.4.2.5","7.4.3.1","8.0.0.34","8.0.1.2","8.0.3.1","8.0.7.0","8.0.8.1","8.0.9.7","8.1.0","8.1.1","8.1.2","8.2.0","8.2.1","8.2.2","8.2.3","8.2.4","8.2.5","8.2.6","8.3.0","8.3.1","8.3.3","8.3.4","8.4.2","8.4.5","8.4.6","8.4.9","8.5.0","8.5.1","8.5.2","8.5.3","8.5.4","8.5.5","8.5.7"]

chrome.storage.local.get('previous_version', x => console.log(x.previous_version))
->
8.5.7
```

Please also include the extension version and the Browser (for me 8.5.7 on Firefox). Thanks a lot!

**Comment by Vinzenz-o** [comment] 2022-02-03 12:11
Hi

I have the same popup problem since last release (or maybe one release before). I think I have the problem sonce 8 days or a little more.

Like said in this thread, each time I open Chrome, I have the popup shown in the message of Rfalanga (15 apr 2020).

All Ghostery notifications are checked except the 4th ("Ajoute de nouveaux mouchards à sa bibliothèque de mouchards" ( Google translate: "Adds new snitches to its snitches library")

After this message, I will try to uncheck the 4 first notifications options to see if it's better (but I would like to keep the notifications in the future).

Version history:
`["7.2.1.3","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.3.1.5","7.3.1.12","7.3.2.5","7.3.3.7","7.4.0.5","7.4.1.4","7.4.2.5","7.4.3.1","8.0.0.34","8.0.1.2","8.0.2.5","8.0.3.1","8.0.4.4","8.0.5.1","8.0.6.2","8.0.7.0","8.0.8.1","8.0.9.7","8.1.0","8.1.1","8.1.2","8.1.3","8.2.0","8.2.1","8.2.2","8.2.3","8.2.4","8.2.5","8.2.6","8.3.0","8.3.1","8.3.2","8.3.3","8.3.4","8.4.0","8.4.1","8.4.2","8.4.3","8.4.3.1","8.4.4","8.4.6","8.4.7","8.4.8","8.5.0","8.5.1","8.5.2","8.5.2.1","8.5.3","8.5.4"]`
I don't know why there is all those "7.2.2"...

Previous version:
`8.5.4`

My system:
Ghostery 8.6.1 on Chrome 98.0.4758.82 (Build officiel) (64 bits) [updated while writing this message. Was 97.0.??? just before with same popup problem], W10 64bits.

I will edit my message (if we can edit) after uncheck 4 first notifications option to say if problem persist.

**Comment by philipp-classen** [comment] 2022-02-03 12:36
@Vinzenz-o Thanks a lot! That is really interesting. Note that the version history ends with "8.5.4", but it should be "8.6.1" after the upgrade is detected. So, it looks like the extension is not able to persist that. This was one of the options that I thought could happen, but I could not reproduce myself. But seeing that output is a great clue for us, as it could be the cause of the bug.

Regarding the repeated "7.2.2": I also noticed that on another profile of mine. Perhaps there was a bug in the 7.2.2 version or the release after 7.2.2. From the code, I think the duplicated entries will not result in problems. Still, cleaning up the duplicated entries in the list would make sense (we can filter the list each time it gets updated).

**Comment by philipp-classen** [comment] 2022-02-03 12:51
@Vinzenz-o 

> But, the 3rd option "Contient des promotions de produits" (Google Translate: "Contains product promotions") is always checked again after Chrome restart...

That is also interesting and seems to confirm the theory that the updates to the configuration get lost. Both the information about the previous extension version and the flags are stored at the same place. If you unchecked the "Contient des promotions de produits" flag, but it is checked again after a browser restart, it means that the update got lost (was not written to `chrome.local.storage`).

We'll need to check the code that is responsible for persisting the configuration. If we can track that down and solve it, then I'm optimistic it will solve the popup issue.

**Comment by BennoG** [comment] 2022-02-03 14:33
Same over here with the versions.  current version 8.6.1

version history:

`["8.2.4","8.2.5","8.2.6","8.3.0","8.3.1","8.3.2","8.3.3","8.3.4","8.4.0","8.4.1","8.4.2","8.4.3","8.4.3.1","8.4.4","8.4.6","8.4.7","8.4.8","8.5.0","8.5.1","8.5.2","8.5.2.1","8.5.3","8.5.4"]`

previous version:

`8.5.4`

current version 8.6.1

Benno

**Comment by philipp-classen** [comment] 2022-02-03 15:59
Thanks for the feedback that really helps us to narrow it down!

In the past, we had occasionally issues with broken profiles (more on Firefox, less on Chrome): all write operations were failing and there was nothing that we could do, as it was a rare browser bug; only uninstalling and reinstalling (to force a new local profile) solved it. Or restoring the local profile from a backup if you have one.

These are exceptional events, so they are difficult to reproduce; but given the user base of Ghostery, it happens from time to time. To test the theory, could you please try to change settings (e.g. disabling the adblocker, turning off options in the settings, trusting pages) and check whether at least one the changes is preserved after a browser restart.

If one setting could be changed, then it means the extension can still write values. But if changes are always lost, it could be that the browser somehow corrupted the profile. In the best case, there would be errors in the console (`about:debugging` or `chrome://extensions`) to confirm it, but even that is not guaranteed.

**Comment by BennoG** [comment] 2022-02-03 16:32
I have the following errors in the log
`Error in event handler: TypeError: Error in invocation of tabs.executeScript(optional integer tabId, extensionTypes.InjectDetails details, optional function callback): Error at parameter 'tabId': Value must be at least 0.
    at s (chrome-extension://mlomiejdfkolichcflejclcbmpeaniij/dist/background.js:843:737)
    at _frameListener (chrome-extension://mlomiejdfkolichcflejclcbmpeaniij/dist/background.js:843:860)`

and

`Uncaught (in promise) Message limit exceeded (action: attrack.keysv2, tag: 7bd383479d783bd1550b7f7d954665a4, limit: 1 per 24 hours)
    at x._signMessage (chrome-extension://mlomiejdfkolichcflejclcbmpeaniij/dist/background.js:1169:12732)
    at async x._send (chrome-extension://mlomiejdfkolichcflejclcbmpeaniij/dist/background.js:1169:14492)
    at async x.send (chrome-extension://mlomiejdfkolichcflejclcbmpeaniij/dist/background.js:1169:12528)`

and

`DevTools failed to load source map: Could not load content for http://localhost:4300/modules/hpnv2/worker.wasm.bundle.js.map: Fetch through target failed: Target not supported; Fallback: Connection error: net::ERR_CONNECTION_REFUSED`

looks like settings in the configuration are saved ok.

**Comment by BennoG** [comment] 2022-02-03 16:39
![image](https://user-images.githubusercontent.com/12594062/152386664-b268de50-23af-4d78-9a99-7517dd2489bf.png)

don't know what to make of this.
but there was the popup after this refresh F5 of the githup page.

**Comment by philipp-classen** [comment] 2022-02-03 18:28
@BennoG Thanks for checking! Just for clarification, when you say that settings in the configuration are saved, did it also work when you restart the browser? Or is the change of the settings then lost (e.g. if you disable adblocking, but after a restart of the browser it is enabled again)?

(Background: the extension will always change the values in memory, but the question is whether the extension is able to flush the changes to disk. If the setting is still changed after a restart of the browser, it means it was able to write something to disk.)

Regarding the errors: For the first one `Error in invocation of tabs.executeScript`, I'm not sure (will keep it in mind). The other two (`Message limit exceeded` and `DevTools failed to load source map`) should be unrelated.

**Comment by Vinzenz-o** [comment] 2022-02-03 18:52
@philipp-classen 
I have just tested to disable Ghostery on this page with the button "Se fier à ce site" ("Trust this site").
Button "Trust this site" is green.
Refresh with the link in the green headband that appear after click on "Trust this site".
"Trust this site" stay green.
Refresh with F5, button "Trust this site" stay green.
Closed the tab then reload the tab, button stay green.

I closed Chrome
Restart Chrome
Ghostery lost the "Trust this site"

So, like you say, ghostery keep un memory the configuration while the browser stay open, but lost it when I restart the browser.

PS: My notifcations options like say in previous message stay unchecked except the third one, either if I close/re-open Chrome.
So, at least for the 2 first options, Ghostery seem to have write the configuration on disk.

**Comment by BennoG** [comment] 2022-02-04 07:23
Ok strange,
Trust site wont survive a restart of Ghostery.
While enable disable show popup when there are new features will survive a restart of chrome browser.

Benno

**Comment by philipp-classen** [comment] 2022-02-04 19:02
The observation that some values can be written, while other write attempt silently fail is a nice clue. It makes the broken profile theory unlikely, but another theory much more likely:

Chrome has a default quota of 5 MB on chrome.local.storage (`chrome.storage.local.QUOTA_BYTES` is 5242880). It is possible to exceed that, for instance, on my own personal profile I'm above it (Firefox allows more then 5 MB). If you exceed that limit, write operations will be rejected (`'QUOTA_BYTES quota exceeded`). Yet some write operation might still work if they stay below the quota (e.g. updating values).

This is the code, but unfortunately the error messages will not be visible in production (we should fix that): 

https://github.com/ghostery/ghostery-extension/blob/b3837ae1aa4b0111034f5fbb73ea8db104246866/src/utils/common.js#L133

Just did a test where I intentionally filled up the storage, and now I could also reproduce a situation where the popup reappears after each extension (or browser) restart. At the same time, the observation that some updates to the settings are lost, is also what I saw.

Perhaps there are other situations where the bug can be triggered, but this is now a concrete case that we can address in the upcoming release. The first step is to free up space by deleting obsolete entries (https://github.com/ghostery/ghostery-extension/issues/747). Also, we need to ensure that the error messages gets printed when the quota is exceed.

Until then, this is how you can check whether you are affected:

```
// (Chrome only): prints the quota (for me it is 5242880 == 5 MB)
chrome.storage.local.QUOTA_BYTES

// estimates the size that is currently used: 
chrome.storage.local.get(null, (data) => { console.table(Object.values(data).map(v => (typeof v === 'string' ? v : JSON.stringify(v)).length).reduce((x,y) => x+y)); });
```

If you are near the limit and have an old profile, you can try to free up some space by removing some dead keys manually. We will a next release soon (next week, I hope); it will automate the cleanup (https://github.com/ghostery/ghostery-extension/issues/747). In the meantime, you can also delete the keys yourself if you don't want to wait for it. To be safe, please create a backup of your profile first before running the command:

```
chrome.storage.local.remove(['storedOffers', 'resource-loader:cliqz:hpn:routeTable.json', 'hpn:localTemporalUniq']);
```

@Vinzenz-o @BennoG : Thank you again for helping us to track that one down! Maybe there are other situation where the bugs occurs, but we are getting closer. :-)

**Comment by tsmorrill** [comment] 2022-04-21 10:49
I am getting this on Ghostery 8.7.0.

**Comment by BennoG** [comment] 2022-04-21 12:25
Yes it is back again with 8.7.0 it was gone for 2 months and it is now back again.

Benno

**Comment by philipp-classen** [comment] 2022-04-21 15:18
Thanks for the feedback! That means, #750 did not solve it (either it is not related to the 5 MB local storage quota, or the attempt to free space by deleting obsolete keys was not enough). Unfortunately, we still cannot reproduce locally.

The previous changes in #750 should have improved the error messages. Maybe there is now an error message or stack trace that helps to narrow it done?

**Comment by tsmorrill** [comment] 2022-04-21 22:20
I am running Firefox 99 and Ghostery 8.7.0. Using the commands posted earlier in the thread, my version history is
`["8.1.0","8.1.1","8.1.2","8.2.0","8.2.1","8.2.3","8.2.4","8.2.5","8.2.6","8.3.0","8.3.1","8.3.2","8.3.3","8.3.4","8.4.2","8.4.5","8.4.6","8.4.9","8.5.0","8.5.1","8.5.2","8.5.3","8.5.4","8.5.5","8.5.7","8.6.2"]`
and my previous version is 8.6.2.

**Comment by wendall911** [comment] 2022-04-23 23:26
@tsmorrill It's probably the stupid Tracker-Tally that was turned on by default... Another thing that needs unchecked after an update. I really wish Ghostery would get a clue and please for the love of everything stop with the popup spam. I mean for a blocker type addon, you'd think that this type of bad behavior would be reserved for spammers, not legitimate apps. I'm sure you'll delete this post, but this has literally been a complaint from users for YEARS. Please just stop it. I'm hoping Mozilla will pull this from the recommended apps as the marketing spam is just out of control

**Comment by philipp-classen** [comment] 2022-04-25 22:21
Cleaning up obsolete keys with the last release was not enough (only for users that had very old installations). It is still possible to hit the 5 MB limit in chrome.storage.local on Chrome.

I'm able to reproduce it in lab conditions now by simulating using the extension over a long period. But as written before in the thread, on my own Firefox profile it was also above the 5 MB limit of Chrome (but not hit by the bug, as Firefox has no limit on the local storage size). So, it is definitely possible to reach it by normal usage; if you keep using Ghostery long enough under Chrome, you might eventually run into the bug.

From my understanding, here are the requirements that lead to the bug:

1. You have to use a Chrome-based Browser (Chrome, Edge, Opera; it is not possible to trigger it on Firefox)
2. Most likely, you have been using the extension for multiple years
3. (optional) You have seen already some extension updates (the "7.2.2","7.2.2","7.2.2" duplicates that we witnessed before made it easier to end up with a long list)

If you are near the quota, some write operations will start failing. Then you may end up in a state, where it fails to update the versions array. Especially, if the version history list is long, it increases the chance that the write operation will blow the quota. Then the following happens: after each startup, the extension will believe it is an extension update and will show the popup.

Since the last release, there is now an error message that you should see in that case (it was not logged before):

```
background.js:163746 10:56:14 PM	 prefsSet ERROR {message: 'QUOTA_BYTES quota exceeded'}
alwaysLog @ background.js:163746
(anonymous) @ background.js:163831
background.js:163748 console.trace
alwaysLog @ background.js:163748
(anonymous) @ background.js:163831

background.js:163832 Uncaught (in promise) Error: [object Object]
    at background.js:163832:16
```
 
![quota-exceeded-bug](https://user-images.githubusercontent.com/1616509/165175908-91e16f42-a5b7-40ab-871f-ad013963518f.png)

---

How to fix it? In a nutshell, we have to make sure that we always stay under the 5 MB quota of Chrome; otherwise, the extension enters undefined state and will start to behave erratic. The popup bug is the most visible, but losing settings over restarts is also nasty.

Now that we understood it better, we will soon push a release that addresses the 5 MB API limit. I'm now confident that it is the reason for the bug and hopefully some other rare ones as well. Sorry for the annoyance with the popup. But thank you again for helping us to track down an important class of errors!

**Comment by tsmorrill** [comment] 2022-04-26 01:15
@philipp-classen Is there more information that you would like me to provide about my Firefox install? I appreciate the amount of work that you put in, but it sounds like the next version you mention will not address the issue on my system.

**Comment by philipp-classen** [comment] 2022-04-26 09:38
@tsmorrill Interested, I overlooked that you are on Firefox. From the update history that you posted, I also think the extension is unable to update the history (`8.7.0` is missing). For instance, on my Firefox profile, it now looks like that (after upgrading to Ghostery `8.7.0`):

`["7.2.0.25","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.2.2","7.3.1","7.3.1.12","7.3.2.5","7.3.3.7","7.4.0.5","7.4.1.4","7.4.2.5","8.0.2.4","8.0.2.5","8.0.3.1","8.0.4.4","8.0.5.1","8.0.6.1","8.0.7.0","8.0.7.1","8.0.8.1","8.0.9.7","8.1.0","8.1.1","8.1.2","8.2.0","8.2.1","8.2.2","8.2.3","8.2.4","8.2.5","8.2.6","8.3.0","8.3.1","8.3.2","8.3.3","8.3.4","8.4.2","8.4.5","8.4.6","8.4.9","8.5.0","8.5.1","8.5.2","8.5.3","8.5.4","8.5.5","8.5.7","8.6.2","8.7.0"]
`

Perhaps you see some error message in `prefsSet ERROR` as well? For instance, in the Chrome experiment, I got `prefsSet ERROR {message: 'QUOTA_BYTES quota exceeded'}`, but maybe there is another reason why a write could fail on Firefox?

One thing to check is to change some settings in the Ghostery extension, restart the browser and check if it was able to remember the changes. If not, it means that it is unable to write to `chrome.storage`.

There is always the small chance that it is a bug in the browser itself and that the extension profile got corrupted. In that case, only reinstalling the extension would help.

**Comment by tsmorrill** [comment] 2022-04-28 12:34
Ok, Ghostery is not able to save my settings after restarting Firefox. I don't see `prefsSet ERROR` in the debugger.

I do get multiple warnings about Cliqz,

```
Content Security Policy: Couldn’t parse invalid host 'wasm-eval'
Cliqz [warning] setting pref logger.telemetry.level before prefs were initialised, you will not get the correct result [background.js:569:417](moz-extension://a544d51d-ef29-f047-9762-e67631413734/dist/background.js)
Cliqz [warning] setting pref logger.pacemaker.level before prefs were initialised, you will not get the correct result background.js:569:417
Cliqz [warning] setting pref logger.core.level before prefs were initialised, you will not get the correct result 2 [background.js:569:417](moz-extension://a544d51d-ef29-f047-9762-e67631413734/dist/background.js)
Cliqz [warning] setting pref logger.human-web.level before prefs were initialised, you will not get the correct result background.js:569:417
Cliqz [warning] setting pref logger.hpnv2.level before prefs were initialised, you will not get the correct result [background.js:569:417](moz-extension://a544d51d-ef29-f047-9762-e67631413734/dist/background.js)
Cliqz [warning] setting pref logger.webrequest-pipeline.level before prefs were initialised, you will not get the correct result background.js:569:417
Cliqz [warning] setting pref logger.antitracking.level before prefs were initialised, you will not get the correct result [background.js:569:417](moz-extension://a544d51d-ef29-f047-9762-e67631413734/dist/background.js)
Cliqz [warning] setting pref logger.adblocker.level before prefs were initialised, you will not get the correct result background.js:569:417
Cliqz [warning] setting pref logger.anolysis.level before prefs were initialised, you will not get the correct result 2 [background.js:569:417](moz-extension://a544d51d-ef29-f047-9762-e67631413734/dist/background.js)
Cliqz [warning] setting pref logger.antiphishing.level before prefs were initialised, you will not get the correct result background.js:569:417
Cliqz [warning] setting pref logger.insights.level before prefs were initialised, you will not get the correct result [background.js:569:417](moz-extension://a544d51d-ef29-f047-9762-e67631413734/dist/background.js)
Cliqz [warning] setting pref logger.hpn-lite.level before prefs were initialised, you will not get the correct result background.js:569:417
Cliqz [warning] setting pref logger.human-web-lite.level before prefs were initialised, you will not get the correct result [background.js:569:417](moz-extension://a544d51d-ef29-f047-9762-e67631413734/dist/background.js)
Cliqz [warning] setting pref logger.life-cycle.level before prefs were initialised, you will not get the correct result 12 background.js:569:417
Cliqz [warning] Storage not available, fallback to in-memory DOMException: IDBDatabase.transaction: 'kv' is not a known object store name
```

as well as the following errors while loading lifecycle:insights

```
[lifecycle:insights] already loaded [background.js:1711:1341](moz-extension://a544d51d-ef29-f047-9762-e67631413734/dist/background.js)
[lifecycle:adblocker] already loaded background.js:1711:1341
[lifecycle:antitracking] already loaded
```

**Comment by 0ki** [comment] 2022-05-25 21:17
What is the current workaround?


I can't seem to find the settings being referred to here:
https://github.com/ghostery/ghostery-extension/issues/500#issuecomment-593437885

**Comment by philipp-classen** [comment] 2022-05-30 15:12
Was mentioned in a commit message, and Github closed it. Reopened now.

**Comment by philipp-classen** [comment] 2022-08-02 12:27
Closing it now, since there was no more activity. It is likely that https://github.com/ghostery/ghostery-extension/issues/777 finally solved the remaining parts. Thanks to everyone for helping us out!

Should you still be affected by the bug, feel free to leave a comment and reopen it, or create a new issue.

**Closed by philipp-classen** 2022-08-02 12:27 UTC
Labels: Type: Bug
