### ISSUE TITLE
Contentful access_token modified

### ISSUE THREAD

**Issue by muhammadbilalplt** [ghostery/ghostery-extension#734] opened 2021-12-10 09:32 UTC
### Description

When sending a client side request to Contentful CDN, we are seeing the access_token being modified and is causing the request to fail/401.

### Expected Behavior

Request should have correct access_token and 200 OK response should be received

### Actual Behavior

Request blocked

### Steps to Reproduce

Request CDN data using SpaceID/Access token.

### Versions

+ Browser: Chrome
+ OS: MacOS
+ Node: 16
+ NPM: 7

**Comment by chrmod** [comment] 2022-01-03 10:51
Ghostery's Anti-Tracking may neutralize unique identifiers from 3rd-party requests https://0x65.dev/blog/2019-12-19/blocking-tracking-without-blocking-trackers.html

Can you please share details on the context of your failure? What's the website URL and what's the URL of the request that fails.

CDNs in regular use case should not require an access token, so this situation is not something that should happen on scale.

**Comment by muhammadbilalplt** [comment] 2022-01-03 20:00
> Ghostery's Anti-Tracking may neutralize unique identifiers from 3rd-party requests https://0x65.dev/blog/2019-12-19/blocking-tracking-without-blocking-trackers.html
> 
> Can you please share details on the context of your failure? What's the website URL and what's the URL of the request that fails.
> 
> CDNs in regular use case should not require an access token, so this situation is not something that should happen on scale.

Anything from this
https://www.contentful.com/developers/docs/references/content-delivery-api/#/introduction/authentication

**Comment by philipp-classen** [comment] 2022-01-04 12:55
Confirmed, it is a false-positive. Contentful requests include a access_token field, even though they are not secrets but shared by all users. As it looks like a strong identifier being used on multiple sites, it triggers our heuristics (and access_token will be replaced by `access_token=ghostery`).

To reproduce with a fresh installation of the extension:
* Visit: https://spyscape.com/
* Visit: https://www.spycon.com/
* Go back to https://spyscape.com/ (now the navigation back is missing, as the CDN requests fail)

**Comment by mhxbe** [comment] 2022-02-18 13:08
We received 2 messages from clients that specific parts (footer) of our website was missing.
After live debugging with one of them, we noticed that the Ghostery Extension was the culprit.

After reading @philipp-classen's write up, we can confirm that this is the problem.

**Comment by philipp-classen** [comment] 2022-05-04 20:02
Have been debugging it again now to understand exactly what happens on the client-side. The test scenario is like describe above:
* Visit 1: https://spyscape.com/
* Visit 2: https://www.spycon.com/
* Visit 3: https://spyscape.com/  (again)

Client-side:
* Visit 1: Ghostery sees a request to `cdn.contentful.com` containing the following URL parameter: `access_token=GBmkx9S7sbqmcEQxPH9FN2qvKdUdUXIlQ5EWeTSDAa8`. Its value triggers a heuristic that scans for potential tracking parameters, but because the value has not been seen before, the request is not modified.
* Visit 2:  Ghostery sees again a request to `cdn.contentful.com` with the same parameter. As the parameter has been now seen on  two different domains, it is considered a tracking parameter and thus replaced. (Note: here, the big question is why on the global aggregation on the server side, this value is not marked as safe.)
* Visit 3: Like in visit 2, the request is modified.

In isolation, the decision from the client is correct. But since we know that all clients will see the identical value, it should be possible to detect globally (on the server side) that it is harmless. To understand the server-side, we also have to look at the messages that the clients sends:

When I run it into debug mode, the following messages are being sent:

```
{"type": "humanweb", "action": "attrack.tp_events", "payload": {"data": [{"hostname": "778c3cce33f4c722", "path": "6666cd76f9695646", "scheme": "https", "c": 1, "t": 27875, "active": 8088, "counter": 1, "ra": 0, "tps": {"assets-global.website-files.com": {"c": 18, "type_4": 1, "scheme_https": 18, "window_depth_0": 18, "referer_leak_header": 13, "resp_ob": 18, "content_length": 6492378, "status_200": 17, "type_2": 1, "type_3": 15, "type_15": 1, "status_206": 1, "cached": 18}, "assets.spyscape.net": {"c": 1, "type_4": 1, "scheme_https": 1, "window_depth_0": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 1, "status_200": 1, "cached": 1}, "spyscape.com": {"c": 7, "type_2": 3, "scheme_https": 7, "window_depth_0": 7, "type_4": 3, "referer_leak_header": 5, "resp_ob": 5, "content_length": 34343, "status_302": 2, "status_200": 2, "type_11": 1, "status_401": 1, "cached": 2, "not_cached": 1}, "js.hsforms.net": {"c": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 1, "status_200": 1, "cached": 1}, "d3e54v103j8qbb.cloudfront.net": {"c": 1, "has_qs": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 1, "status_200": 1, "cached": 1}, "d1igp3oop3iho5.cloudfront.net": {"c": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "blocked_external": 1, "error_abort": 1}, "www.googletagmanager.com": {"c": 1, "has_qs": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "blocked_external": 1}, "assets.website-files.com": {"c": 7, "type_14": 7, "scheme_https": 7, "window_depth_0": 7, "resp_ob": 7, "content_length": 127396, "status_200": 7, "cached": 7}, "cdn.contentful.com": {"c": 2, "has_qs": 2, "type_11": 2, "scheme_https": 2, "window_depth_0": 2, "token.has_qs_countThreshold": 1, "token.qs_countThreshold": 1, "token.has_no_check": 2, "token.no_check": 5, "token.has_safekey": 2, "token.safekey": 2, "bad_qs": 1, "bad_tokens": 1, "token_blocked_placeholder": 1, "hasPlaceHolder": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 202, "status_401": 1, "not_cached": 1}, "forms.hsforms.com": {"c": 2, "has_qs": 2, "type_11": 2, "scheme_https": 2, "window_depth_0": 2, "token.has_no_check": 2, "token.no_check": 2, "referer_leak_header": 2, "resp_ob": 2, "content_length": 19, "status_200": 2, "not_cached": 2}, "cdn.embedly.com": {"c": 1, "has_qs": 1, "type_7": 1, "scheme_https": 1, "window_depth_1": 1, "token.has_no_check_decoded": 1, "token.no_check_decoded": 3, "token.has_no_check": 1, "token.no_check": 4, "token.has_whitelisted": 1, "token.whitelisted": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 1, "status_200": 1, "cached": 1}, "maps.googleapis.com": {"c": 28, "has_qs": 21, "type_2": 14, "scheme_https": 28, "window_depth_0": 28, "referer_leak_header": 27, "resp_ob": 27, "content_length": 560940, "status_200": 27, "type_11": 1, "blocked_external": 1, "type_3": 13, "referer_leak_site": 3, "referer_leak_path": 3, "not_cached": 6, "error_abort": 1, "cached": 21}, "player.vimeo.com": {"c": 1, "has_qs": 1, "type_7": 1, "scheme_https": 1, "window_depth_2": 1, "token.has_whitelisted": 1, "token.whitelisted": 1, "token.has_no_check_decoded": 1, "token.no_check_decoded": 1, "referer_leak_site": 1, "referer_leak_path": 1, "cookie_set": 1, "cookie_allow_ghostery": 2, "resp_ob": 1, "content_length": 1, "status_200": 1, "set_cookie_set": 1, "set_cookie_samesite_none": 1, "not_cached": 1}, "i.vimeocdn.com": {"c": 2, "has_qs": 2, "type_3": 2, "scheme_https": 2, "window_depth_2": 2, "token.has_no_check": 2, "token.no_check": 4, "resp_ob": 2, "content_length": 23432, "status_200": 2, "cached": 2}, "f.vimeocdn.com": {"c": 3, "type_2": 2, "scheme_https": 3, "window_depth_2": 3, "type_4": 1, "resp_ob": 3, "content_length": 220769, "status_200": 3, "cached": 3}, "maps.gstatic.com": {"c": 4, "type_3": 4, "scheme_https": 4, "window_depth_0": 4, "referer_leak_header": 4, "resp_ob": 4, "content_length": 2228, "status_200": 4, "cached": 4}, "fresnel.vimeocdn.com": {"c": 2, "has_qs": 2, "has_post": 2, "type_10": 2, "scheme_https": 2, "window_depth_2": 2, "blocked_external": 2, "error_abort": 2}, "fonts.googleapis.com": {"c": 2, "has_qs": 2, "type_4": 2, "scheme_https": 2, "window_depth_0": 2, "referer_leak_header": 2, "resp_ob": 2, "content_length": 2, "status_200": 2, "cached": 2}, "fonts.gstatic.com": {"c": 2, "type_14": 2, "scheme_https": 2, "window_depth_0": 2, "resp_ob": 2, "content_length": 31608, "status_200": 2, "cached": 2}}, "placeHolder": false, "redirects": [], "redirectsPlaceHolder": [], "triggeringTree": {}, "tsv": "", "tsv_id": false, "frames": {}}], "ts": "2022050418", "conf": {}, "addons": false, "ver": "0.102", "ctry": "de"}, "platform": "", "userAgent": "chrome", "channel": "ghostery", "ts": "20220504", "anti-duplicates": 5813551, "sender": "hpnv2"}
{"action": "attrack.tokensv2", "payload": {"data": [{"ts": "20220504", "token": "0a0f55d83f3ead2d382e59cba21b9550", "safe": false, "sites": 2, "trackers": 1}], "ts": "2022050418", "day": "2022-05-02", "ver": "0.102", "ctry": "de"}, "type": "humanweb", "platform": "", "userAgent": "chrome", "channel": "ghostery", "ts": "20220504", "anti-duplicates": 9636556, "sender": "hpnv2"}
{"type": "humanweb", "action": "attrack.tp_events", "payload": {"data": [{"hostname": "d7069036378e349a", "path": "6666cd76f9695646", "scheme": "https", "c": 1, "t": 46548, "active": 6262, "counter": 0, "ra": 0, "tps": {"assets-global.website-files.com": {"c": 20, "type_4": 1, "scheme_https": 20, "window_depth_0": 20, "referer_leak_header": 11, "resp_ob": 20, "content_length": 3092601, "status_200": 19, "type_2": 1, "type_3": 17, "type_15": 1, "status_206": 1, "cached": 20}, "ajax.googleapis.com": {"c": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 5437, "status_200": 1, "cached": 1}, "cdn.finsweet.com": {"c": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 1, "status_200": 1, "cached": 1}, "js.hsforms.net": {"c": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 1, "status_200": 1, "cached": 1}, "d3e54v103j8qbb.cloudfront.net": {"c": 1, "has_qs": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 1, "status_200": 1, "cached": 1}, "fonts.googleapis.com": {"c": 1, "has_qs": 1, "type_4": 1, "scheme_https": 1, "window_depth_0": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 1, "status_200": 1, "cached": 1}, "apps.elfsight.com": {"c": 2, "type_2": 1, "scheme_https": 2, "window_depth_0": 2, "referer_leak_header": 2, "resp_ob": 2, "content_length": 2, "status_301": 1, "has_qs": 1, "type_11": 1, "status_200": 1, "set_cookie_set": 1, "set_cookie_samesite_none": 1, "cookie_allow_ghostery": 1, "not_cached": 1}, "www.googletagmanager.com": {"c": 1, "has_qs": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "blocked_external": 1}, "d1igp3oop3iho5.cloudfront.net": {"c": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "blocked_external": 1, "error_abort": 1}, "cdn.jetboost.io": {"c": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 1, "status_200": 1, "cached": 1}, "assets.website-files.com": {"c": 5, "type_14": 5, "scheme_https": 5, "window_depth_0": 5, "resp_ob": 5, "content_length": 82957, "status_200": 5, "cached": 5}, "cdn.contentful.com": {"c": 1, "has_qs": 1, "type_11": 1, "scheme_https": 1, "window_depth_0": 1, "token.has_qs_newToken": 1, "token.qs_newToken": 1, "token.has_no_check": 1, "token.no_check": 2, "token.has_safekey": 1, "token.safekey": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 10847, "status_200": 1, "cached": 1}, "static.elfsight.com": {"c": 2, "type_2": 2, "scheme_https": 2, "window_depth_0": 2, "referer_leak_header": 2, "resp_ob": 2, "content_length": 2, "status_200": 2, "cached": 2}, "forms.hsforms.com": {"c": 2, "has_qs": 2, "type_11": 2, "scheme_https": 2, "window_depth_0": 2, "token.has_safekey": 2, "token.safekey": 2, "referer_leak_header": 2, "resp_ob": 2, "content_length": 19, "status_200": 2, "not_cached": 2}, "fonts.gstatic.com": {"c": 10, "type_14": 10, "scheme_https": 10, "window_depth_0": 10, "resp_ob": 10, "content_length": 221260, "status_200": 10, "cached": 10}, "images.ctfassets.net": {"c": 7, "type_3": 7, "scheme_https": 7, "window_depth_0": 7, "referer_leak_header": 7, "resp_ob": 7, "content_length": 7, "status_200": 7, "cached": 7}, "scp2.elfsightcdn.com": {"c": 20, "has_qs": 20, "type_3": 20, "scheme_https": 20, "window_depth_0": 20, "referer_leak_header": 20, "resp_ob": 20, "content_length": 199308, "status_200": 20, "cached": 19, "not_cached": 1}}, "placeHolder": false, "redirects": [], "redirectsPlaceHolder": [], "triggeringTree": {}, "tsv": "", "tsv_id": false, "frames": {}}], "ts": "2022050418", "conf": {}, "addons": false, "ver": "0.102", "ctry": "de"}, "platform": "", "userAgent": "chrome", "channel": "ghostery", "ts": "20220504", "anti-duplicates": 8820442, "sender": "hpnv2"}
{"type": "humanweb", "action": "attrack.tp_events", "payload": {"data": [{"hostname": "d7069036378e349a", "path": "6666cd76f9695646", "scheme": "https", "c": 1, "t": 7567, "active": 4611, "counter": 1, "ra": 0, "tps": {"assets-global.website-files.com": {"c": 2, "type_4": 1, "scheme_https": 2, "window_depth_0": 2, "referer_leak_header": 2, "resp_ob": 2, "content_length": 131236, "status_200": 2, "cached": 2, "type_3": 1}, "js.hsforms.net": {"c": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 1, "status_304": 1, "not_cached": 1}, "apps.elfsight.com": {"c": 2, "type_2": 1, "scheme_https": 2, "window_depth_0": 2, "referer_leak_header": 2, "resp_ob": 2, "content_length": 2, "status_301": 1, "has_qs": 1, "type_11": 1, "status_200": 1, "set_cookie_set": 1, "set_cookie_samesite_none": 1, "cookie_allow_ghostery": 1, "not_cached": 1}, "fonts.googleapis.com": {"c": 1, "has_qs": 1, "type_4": 1, "scheme_https": 1, "window_depth_0": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 1, "status_200": 1, "cached": 1}, "www.googletagmanager.com": {"c": 1, "has_qs": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "blocked_external": 1}, "d1igp3oop3iho5.cloudfront.net": {"c": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "blocked_external": 1, "error_abort": 1}, "cdn.jetboost.io": {"c": 1, "type_2": 1, "scheme_https": 1, "window_depth_0": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 1, "status_200": 1, "cached": 1}, "cdn.contentful.com": {"c": 2, "has_qs": 2, "type_11": 2, "scheme_https": 2, "window_depth_0": 2, "token.has_qs_countThreshold": 1, "token.qs_countThreshold": 1, "token.has_no_check": 2, "token.no_check": 5, "token.has_safekey": 2, "token.safekey": 2, "bad_qs": 1, "bad_tokens": 1, "token_blocked_placeholder": 1, "hasPlaceHolder": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 202, "status_401": 1, "not_cached": 1}, "static.elfsight.com": {"c": 2, "type_2": 2, "scheme_https": 2, "window_depth_0": 2, "referer_leak_header": 2, "resp_ob": 2, "content_length": 2, "status_200": 2, "cached": 2}, "forms.hsforms.com": {"c": 1, "has_qs": 1, "type_11": 1, "scheme_https": 1, "window_depth_0": 1, "token.has_safekey": 1, "token.safekey": 1, "referer_leak_header": 1, "resp_ob": 1, "content_length": 1, "status_200": 1, "not_cached": 1}}, "placeHolder": false, "redirects": [], "redirectsPlaceHolder": [], "triggeringTree": {}, "tsv": "", "tsv_id": false, "frames": {}}], "ts": "2022050418", "conf": {}, "addons": false, "ver": "0.102", "ctry": "de"}, "platform": "", "userAgent": "chrome", "channel": "ghostery", "ts": "20220504", "anti-duplicates": 7730339, "sender": "hpnv2"}
{"action": "attrack.keysv2", "payload": {"data": [{"ts": "20220504", "tracker": "b29b0c79e280a18c", "key": "d86c828583c5c6160e8acfee88ba1590", "site": "d7069036378e349a", "tokens": [["0a0f55d83f3ead2d382e59cba21b9550", false]]}], "ts": "2022050418", "day": "2022-05-02", "ver": "0.102", "ctry": "de"}, "type": "humanweb", "platform": "", "userAgent": "chrome", "channel": "ghostery", "ts": "20220504", "anti-duplicates": 9588270, "sender": "hpnv2"}
{"action": "attrack.keysv2", "payload": {"data": [{"ts": "20220504", "tracker": "b29b0c79e280a18c", "key": "d86c828583c5c6160e8acfee88ba1590", "site": "cd3f62181a75fd16", "tokens": [["0a0f55d83f3ead2d382e59cba21b9550", false]]}], "ts": "2022050418", "day": "2022-05-02", "ver": "0.102", "ctry": "de"}, "type": "humanweb", "platform": "", "userAgent": "chrome", "channel": "ghostery", "ts": "20220504", "anti-duplicates": 5524753, "sender": "hpnv2"}
{"action": "attrack.keysv2", "payload": {"data": [{"ts": "20220504", "tracker": "b29b0c79e280a18c", "key": "0559c14ffc525fceb92bb20ac4463bb2", "site": "d7069036378e349a", "tokens": [["bef4b6d44cd4570bcead60799ede7fc2", true]]}], "ts": "2022050418", "day": "2022-05-02", "ver": "0.102", "ctry": "de"}, "type": "humanweb", "platform": "", "userAgent": "chrome", "channel": "ghostery", "ts": "20220504", "anti-duplicates": 9177189, "sender": "hpnv2"}
{"action": "attrack.keysv2", "payload": {"data": [{"ts": "20220504", "tracker": "b29b0c79e280a18c", "key": "0559c14ffc525fceb92bb20ac4463bb2", "site": "cd3f62181a75fd16", "tokens": [["448e0906511d919d2a37682ea4213f4f", true]]}], "ts": "2022050418", "day": "2022-05-02", "ver": "0.102", "ctry": "de"}, "type": "humanweb", "platform": "", "userAgent": "chrome", "channel": "ghostery", "ts": "20220504", "anti-duplicates": 1696055, "sender": "hpnv2"}
```

To understand the messages better, here is how the client mapped potentially sensitive information to hashes (instead of sending them as clear text):

* `0a0f55d83f3ead2d382e59cba21b9550` (derived from the value of the `access_token` parameter, which is `GBmkx9S7sbqmcEQxPH9FN2qvKdUdUXIlQ5EWeTSDAa8`)
*  `cd3f62181a75fd16`: derived from the domain `spycon.com`
* `d7069036378e349a`: derived from the domain `spyscape.com`

Here is an image of the messages above, where the relevant entries are highlighted:

![contentful_messages](https://user-images.githubusercontent.com/1616509/166813707-ce0a680a-dee7-425e-b3bb-e246bc86fd94.png)

From the client-side, I cannot see any error so far. If enough clients would share that information, the hash of the token should be detected as being safe.

It could be a bug in the aggregation, but my current hypothesis is that there are simply not enough messages to exceed the threshold. When grepping through one day of raw data, I did see entries, but only very few.

---

As a next step, we can test the hypothesis by looking at a larger window. Ideally, we should use the same window size as we use in the aggregation step (I think it is two weeks). Then we should see if there are enough events for that specific token. If there are enough, the small subset of messages should help to narrow it down.

**Comment by philipp-classen** [comment] 2022-06-14 14:06
Looking through two weeks of data, the amount of traffic is quite low. Note that only users that visited at least two sites where the CDN is present will send the events. The total number of events in the period was 21, but to reach quorum, it needs more traffic.

In sum, it looks like it is an edge case: just on the edge of reaching quorum, but not quite making it. That is why the system is not able to proof that the value is safe.

**Comment by smalluban** [comment] 2024-06-17 08:11
Chrome platform migrated to v10. Feel free to re-open if the issue is still valid.

**Closed by smalluban** 2024-06-17 08:11 UTC
Labels: Anti-Tracking

**Comment by philipp-classen** [comment] 2024-06-17 09:48
It is fine to leave it closed, since we did not have reports about it for a while.

But just as a note, the anti-tracking code base and methodology has not changed between Ghostery 8 and 10.
