### ISSUE TITLE
Trackers are already selected after the update, even if they were not previously selected.

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#853] opened 2022-09-05 15:13 UTC
Trackers are already selected after the update, even if they were not previously selected.

Expected Behavior
If previously the User did not select ANY of the tracers to be blocked, after updating to the newest version, the situation shouldn't be changed.

Actual Behavior
After updating to the newest version, all tracers are selected.

Prerequisites:
Download Ghostery Browser Extension in versions 8.7.4 and 8.8.0.

Steps to Reproduce
1. Open Chrome browser and open Settings/ Extensions.
2. Turn on Developer mode.
3. Create a new folder and copy files for version 8.7.4.
4. Load unpacked version 8.7.4 to a newly created folder, and load unpacked extension in Chrome by clicking "Load unpacked".
5. During configuration turn OFF everything:
![obraz](https://user-images.githubusercontent.com/40433708/188478457-96823430-d428-4d0b-bb5c-47f77e6cfacf.png)
![obraz](https://user-images.githubusercontent.com/40433708/188478499-6ea663df-8cc2-4953-af6b-cc3537fc3ecd.png)
6. Go to a newly created folder from step 3 and delete all files and folders. Copy here all the files for version 8.8.0.
7. Close and reopen the Chrome browser.
8. Open Ghostery Browser Extension box and check the configuration:
![obraz](https://user-images.githubusercontent.com/40433708/188478816-42c0a068-a5c4-40c3-adef-e23f3f8d0c4f.png)
![obraz](https://user-images.githubusercontent.com/40433708/188478845-f9b5c06e-eef3-425e-b553-c0bbf8a93c5e.png)

Versions

    Browser: Chrome 104.0.5112.102
    OS: Windows 10
    Version of Ghostery Browser Extension: 8.7.4 -> 8.8.0

**Comment by philipp-classen** [comment] 2022-09-05 15:28
Will have to look into it, but I could now also reproduce:

* Install 8.7.4 on Chrome
* Disable all categories and the three blocking options
* Upgrade to 8.8.0

![after_upgrade](https://user-images.githubusercontent.com/1616509/188481376-b491087e-5f82-4619-add9-1c25ebbf9c4d.png)

This is indeed a weird state after the upgrade.

**Comment by philipp-classen** [comment] 2022-09-05 15:31
I did not include it in the screenshot, but the list of trackers that gets selected (when the bug hits) seems to be non-deterministic.

**Comment by philipp-classen** [comment] 2022-09-05 16:10
Could be a combination of bugs, but this here is most likely a regression:

https://github.com/ghostery/ghostery-extension/blob/d491ba7c9a58d4d4eb05b5229edf9c9f3eed402e/extension-manifest-v2/src/background.js#L1518

Currently, that code always runs at startup unless you are logged in. The effect is that it will enable all trackers of categories that are enabled by default. In other words, if you disable one of the trackers in the default categories (e.g. advertising) and restart the extension, it will be enabled again.

**Comment by philipp-classen** [comment] 2022-09-05 16:17
Looks like there are three bugs:
* 8.7.4: the database is initialized with only a few trackers (not clear why or whether it can also happen on 8.8.0)
* 8.8.0: disabled trackers in categories that are blocked by default will be reset after each reload
* 8.8.0: the button to toggle whole tracking category is gone (see previous screenshot)

**Comment by philipp-classen** [comment] 2022-09-16 10:35
Just saw the third bug (database being initialized with only a few trackers) also with the new code. That means, the bug still exists on the main branch and that it is not only a <=8.7.6 problem

**Comment by philipp-classen** [comment] 2022-09-16 12:28
I opened now a dedicated bug for the open question why the tracker list may start with a limited subset: https://github.com/ghostery/ghostery-extension/issues/872

Closing this one now, since the actual problems that were consistently reproducible should be fixed.

**Closed by philipp-classen** 2022-09-16 12:28 UTC
Labels: Type: Bug
