### ISSUE TITLE
bicmagazine.com

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1215] opened 2023-06-28 10:55 UTC
**Description**
The website is covered by big number of ads which are not blocked.

**Steps to Reproduce**
1. Open https://www.bicmagazine.com/industry/refining-petrochem/lyondellbasell-announces-delay-in-refining-business-exit/?em=dGphY2tzb25Ac3RlYW1zb2x1dGlvbnMuY29t&utm_campaign=IR+06.01.23&fref=924977d0-c7c3-45cc-97ca-a55215ebeaf1

![Chrome](https://github.com/ghostery/broken-page-reports/assets/40433708/ca0e2519-4d49-489d-81c3-f959e676c761)
![Screenshot 2023-06-28 at 12 50 48](https://github.com/ghostery/broken-page-reports/assets/40433708/a204c596-7811-4458-baf8-7501bc42788e)

**Expected results**
Ads should be blocked.

Versions
Browser: Chrome 114.0.5735.199
OS: Windows 10 Pro 19045.2965
GBE 8.10.3

Browser: Opera 100.0.4815.21
OS: Windows 10 Pro 19045.2965
GBE 8.10.3

Browser: Edge 114.0.1823.58
OS: Windows 10 Pro 19045.2965
GBE 8.10.3

Browser: Safari 16.5.1 (18615.2.9.11.7)
OS: MacOS Ventura 13.2.1
GBE 10.0.12

**Comment by smalluban** [comment] 2023-07-07 08:10
The core issue of the problem is in Chromium-based browsers, which set `tabId` to `-1` for Service Worker requests. The above site uses strong caching in SW, and sequential calls for assets are done through the SW. Our current adblocker implementation filters out those requests thinking that they are made from the background process.

@chrmod @philipp-classen The easiest solution would be removing that condition, but I don't have that deep knowledge if it can break anything.

**Comment by philipp-classen** [comment] 2023-07-07 09:40
This here is an experiment that removes it (in both the common and Ghostery Extension layer). A problem is that the code makes assumptions about having the information from the tab (the POC fills in the URL to continue, but it is likely not a sound approach):
* https://github.com/ghostery/ghostery-extension/pull/1223
* https://github.com/ghostery/common/pull/82

**Comment by smalluban** [comment] 2023-07-12 11:57
@chrmod The issue is still open but commits from the 8.11.0 release suggest that the problem is fixed. Can we close it?

https://github.com/ghostery/ghostery-extension/pull/1219/commits/69a54a4180aa538f325711ed648ae360e8790f08

**Comment by philipp-classen** [comment] 2023-07-12 12:07
IMHO, leaving tickets open until the fix is rolled out is best (in this case, at least until Chrome got update). Otherwise, it tends to confuse people who think it should be working already on their machine.

But leaving a comment like the one above about upcoming fixes is always good.

**Comment by smalluban** [comment] 2023-07-12 12:29
I'm not sure. Usually, we write in PR "Fixes #...", so the issue is closed when PR is merged (and it was tested), but before the rollout.

**Comment by philipp-classen** [comment] 2023-07-12 12:58
> I'm not sure. Usually, we write in PR "Fixes #...", so the issue is automatically closed when PR is merged (and it was tested), but before the rollout.

I know, that is the workflow that we have. Since it seems to be a Ghostery internal ticket, we can do it.

But overall, I find the workflow problematic once there is at least one person (a Ghostery user, not a dev) interacting with it. Closing it suggest that it is working now (when it hits the main branch). Then they think it is solved, only to find out that it is still broken. Or even worse, something people thought we close it without fixing it (seeing it as "won't fix").

In the meantime, I tend to use only "refs" instead of "fixes" to avoid that problem. We might have our workflow, but my experience is that everything else thinks "open" means the problem exists and "closed" means "it should be working now (on their device)".

**Closed** 2023-07-18 07:13 UTC
Labels: Type: Ad-Blocking, Chrome, Edge, Opera
