### ISSUE TITLE
google.com refresh loop

### ISSUE THREAD

**Issue by Spongman** [ghostery/ghostery-extension#1206] opened 2023-06-21 00:05 UTC
- go to https://google.com
- enable ghostery
- search for _anything_

**Comment by fcjr** [comment] 2023-06-21 00:09
For a little more context:
Seems to only happen for searches that have youtube (video) results and if you are logged into a google account

**Comment by swipetwenty** [comment] 2023-06-21 04:35
seeing same result starting today.  Version installed on chrome is 8.10.3.

Was able to stop the reloading with a variety of different approaches.   Hope this narrows down where the issue may be.

- disabled ghostery extension in chrome
- in ghostery menu, click on trust site
- in ghostery menu, click Ad-Blocking off
- enable ghostery in incognito and use incognito
- sign out of google account

**Comment by chrmod** [comment] 2023-06-21 07:09
Many thanks for reporting. We can definitely reproduce the problem and can already confirm it is caused by adblocker cosmetic filters. Trying to find the rule that breaks.

**Comment by ConorCorp** [comment] 2023-06-21 07:46
+1

**Comment by chrmod** [comment] 2023-06-21 07:59
This is a rule that breaks google.com:
```
http://youtube.com/##+js(trusted-set-cookie), SOCS, CAESEwgDEgk1MjE4NjcxMTIaAmVuIAEaBgiAl7ihBg, 1year, , reload, 1)
```

It must be a problem with scriptlets injection. 

As a quickfix I'm disabling the rule now and will continue investigation on why it breaks.

**Comment by chrmod** [comment] 2023-06-21 08:44
A fix is now live for all users. To force update adblocker filters use "Update now" button in the General settings.
<img width="581" alt="Screenshot 2023-06-21 at 10 43 28" src="https://github.com/ghostery/ghostery-extension/assets/1228153/7c53c0ec-0a6d-4e5f-8ba0-941ef4c961eb">

**Comment by chrmod** [comment] 2023-06-21 08:57
@Spongman @swipetwenty @ConorCorp 
At Ghostery we value contributions! Please reach out to support@ghostery.com with a link to this issue, so we can send you a coupon code to get access to Contributor extras.
We are happy to have you as a part of the Ghostery Contributors community!

@fcjr great to see you around, many thanks for involvement!

**Comment by chrmod** [comment] 2023-06-21 08:57
Closing the issue as it looks as fixed but will keep it pinned for visibility.

**Closed by chrmod** 2023-06-21 08:57 UTC
Labels: Type: Bug, Type: Ad-Blocking
