### ISSUE TITLE
High processor usage on heise.de

### ISSUE THREAD

**Issue by yokoffing** [ghostery/ghostery-extension#1392] opened 2023-11-21 19:16 UTC
Ghostery causes Firefox to have a high CPU utilization simply when `https://www.heise.de/` is displayed. Also a performance profiling yields Javascript functions being the hottest methods.

URL: https://www.heise.de/
Ghostery version: 8.11.1
Browser name:  Firefox
Browser version:  119.0.1
Language: en
OS: MS Windows 10

Similar to: https://github.com/ghostery/ghostery-extension/issues/757

![task-manager](https://github.com/ghostery/ghostery-extension/assets/11689349/cbe9132a-3e36-465e-bf2c-34bea1fc46b9)

![call-stack](https://github.com/ghostery/ghostery-extension/assets/11689349/97bf5ed0-f751-45da-b0e4-c1ab8076528d)

**Comment by philipp-classen** [comment] 2024-04-11 17:37
The hot path in the screenshot is the same function as here: https://github.com/ghostery/ghostery-extension/issues/757#issuecomment-2050064058

Note to investigate later: it could be that there are frequent DOM mutations near the top of the document. Then iterating over all matches of this expression can become costly:

```
querySelectorAll(
        '[id]:not(html):not(body),[class]:not(html):not(body),[href]:not(html):not(body)'
```

If that is the case, it is most likely not isolated to Firefox, but affects Chrome as well. Only that the overhead in Chrome is not as big (either Chrome does some throttling, or the DOM API or JavaScript engine is faster for this operation).

**Comment by Nahor** [comment] 2024-05-26 19:32
I'm not able to reproduce the issue anymore (Firefox 126.0, Ghostery 8.12.10)

**Comment by philipp-classen** [comment] 2024-05-27 09:51
> I'm not able to reproduce the issue anymore (Firefox 126.0, Ghostery 8.12.10)

Thanks for checking! I will close it.

(Background: The performance bug used to be reproducible with Ghostery when it was installed next to uBlock Origin. But uBlock Origin optimized the scriplet that could cause DOM modification events being spammed: https://github.com/gorhill/uBlock/commit/91dfcbef2a9d1a6557b65eedec8b7f11e87adc8e#diff-30b28769623e5478a0f68519eda037164484cfb444cb5a8e48518fa7bb32e658R2267)

**Closed by philipp-classen** 2024-05-27 09:51 UTC
Labels: Firefox, From Zendesk

**Comment by Nahor** [comment] 2024-05-27 17:48
I'm not sure that this bug was caused by the interaction with uBO. When I tried with uBO disabled, [I was still seeing the issue](https://github.com/ghostery/ghostery-extension/issues/757#issuecomment-2050098703). A further difference with the uBO interaction, is that the CPU was not 100% like on the Reddit website, and as can be seen the screenshot in the top post, where there are gaps in the CPU usage.

I suspect the fix for this bug is in the website itself (or in Firefox)

**Comment by philipp-classen** [comment] 2024-05-27 17:56
> I'm not sure that this bug was caused by the interaction with uBO. When I tried with uBO disabled, [I was still seeing the issue](https://github.com/ghostery/ghostery-extension/issues/757#issuecomment-2050098703). A further difference with the uBO interaction, is that the CPU was not 100% like on the Reddit website, and as can be seen the screenshot in the top post, where there are gaps in the CPU usage.
> 
> I suspect the fix for this bug is in the website itself (or in Firefox)

Good point, I forget that aspect. I remember that I was not able reproduce myself (without uBlock Origin); but there could have been subtle details like screen resolution, etc, which may have had an effect on DOM modifications.
