### ISSUE TITLE
Chrome Tab Middle Click "pop-up blocked"

### ISSUE THREAD

**Issue by LtPatterson** [ghostery/ghostery-extension#313] opened 2019-01-10 14:28 UTC
### Description

Middle clicking a link to open it in a new tab triggers the chrome popup blocker and does not open the new tab. 
Issue was concurrent with issue #310 and is behavior similar to if not exactly the same as #254 , which is a closed issue, so I'm opening a new one in hopes it gets someone's attention. Other users reporting the same problem in #254. 

https://www.reddit.com/r/Ghostery/comments/aedrcs/ghostery_broke_full_screen_video_in_chrome/
https://www.reddit.com/r/chrome/comments/aeeirm/chrome_now_blocks_middle_clicking_to_a_new_tab_on/
https://bugs.chromium.org/p/chromium/issues/detail?id=918268

### Expected Behavior 

A new tab to open when a link is clicked using the middle mouse button.

### Actual Behavior 

Pop-up blocker catches the new tab and does not open it without user intervention/exception acceptance.

### Steps to Reproduce

1. Click a link with middle mouse, expected behavior not occurring.
2. Nothing happens/pop-up blocked

### Versions

+ Browser: Chrome 71.0.3578.98
+ OS: W10
+ Node: 8.2.6
+ NPM:

**Comment by hypercube33** [comment] 2019-01-10 14:52
I can also reproduce this. Disabled the plugin and its working as expected. Happening on multiple sites. May be tied to this reddit thread as well.
https://old.reddit.com/r/chrome/comments/aed4ot/chrome_treating_middleclicks_as_popups/

**Comment by joekaiser** [comment] 2019-01-10 16:54
I can reproduce this. It also blocks with a ctrl+click

**Comment by philipp-classen** [comment] 2019-01-10 19:33
Looks like a duplicate of #314

**Comment by betterwithpesto** [comment] 2019-01-10 19:33
Clicking on a link that has `target="_blank"` that normally opens in a new tab, is now blocked as well when the extension is running.

**Comment by philipp-classen** [comment] 2019-01-11 00:09
@christophertino Can you please mark it as a duplicate of #314

Chrome is rolling back their experiment, which should fix it.

**Closed as completed** 2019-01-14 18:13 UTC
