### ISSUE TITLE
Cliqz - Ghostery Global Blocking list empty - Zero trackers blocked

### ISSUE THREAD

**Issue by nikita81** [ghostery/ghostery-extension#456] opened 2019-09-30 19:26 UTC
On Cliqz Browser Global Blocking list is empty so trackers are not blocked and counter is always at 0.
I've tried to reinstall the extension but it behave the same way.
It works fine with Chrome and Firefox.

+ Browser: Cliqz
+ OS: Linux Mint 19.1 and Windows 10

On Windows 10 I've done a fresh installation of the cliqz browser as well.

**Comment by christophertino** [comment] 2019-10-01 15:09
This is caused by a bug that clears the Ghostery settings from memory each time the browser starts. You may also see the Ghostery on-boarding hub open each time you start Cliqz. 

Partially fixed by https://github.com/ghostery/ghostery-extension/commit/298cd007aacf52226a2f8f0f774543b21ba55556

**Comment by christophertino** [comment] 2019-11-21 18:26
This should be fixed in v8.4.5 which was approved today by AMO.  Please let us know if you still see this issue.

**Closed by christophertino** 2019-11-21 18:26 UTC
