### ISSUE TITLE
Ghostery Chrome Extension blocks Tealium utag.js with 'Add Blocker' feature even though listed in 'Essential' category. Files used as dependency and causes undefined errors

### ISSUE THREAD

**Issue by rsabec** [ghostery/ghostery-extension#562] opened 2020-06-02 19:09 UTC
### Description

Ghostery Version 8.5.0 is applying 'Add Blocker' to the loading of utag.js and utag.sync.js files.  This is a tag management api platform and not directly an 'advertiser' vendor.   Site will use these files as a dependencies that page code will directly call.  Blocking these files will cause undefined errors and break the site. As Tealium's TMS is not tracking users and is a pure TMS, it should not be blocked by default. Additionally, companies use Tealium's TMS to provide their GDPR AND CCPA consent management via this script.

### Expected Behavior

Tealium or the utag.js and utag.sync.js files are currently listed in Ghostery's 'Essential' category.  This tag should only be blocked if 'Essential' tags are blocked. 

### Actual Behavior

Ghostery is blocking the utag.js and utag.sync.js files only when the 'Add Blocker' feature is activated and 'Essential' Trackers are left unblocked.  

### Steps to Reproduce

1. [activate Ghostery's Add Blocker feature]
2. [Navigate to 3m.com]
3. [review network traffic for 'Essential' tag utag.js and utag.sync.js ]
4. review debugger console for 'undefined' errors that are caused by blocking the 'Essential' tag used as a dependency on this site.

### Versions

+ Browser: Chrome Version 81.0.4044.138 (Official Build) (64-bit)
+ OS: mac OS X 10.14.6
+ Node: 
+ NPM:

**Comment by christophertino** [comment] 2020-06-26 16:43
The ad-blocker is catching `tags.tiqcdn.com` from one of its lists (Peter Lowe's Server List). Even though Tealium is unblocked under Essential, that is only a pass-through action and patterns can still be caught by the ad-blocker.  This would be another case for a global allow function (see #148). 

In the meantime, the best solution I can offer would be to either Trust the entire site, or hover over the Tealium tracker and select "Trust on this site".

**Comment by rsabec** [comment] 2020-06-30 16:15
Hi Christopher - I would like to have more context or understanding on why you have listed a 'tag manager' as as 'advertiser'.  I noticed that similar API management platforms such as Google Tag Manager or Adobe DTM are not blocked by the same 'Advertiser' filter.  In these other Tag Manager vendors you have chosen to block the individual tags loading and not the manager entirely.  Why are you classifying Tealium's TIQ product as a 'Advertiser' ?  You reference a'Peter Lowe's Server List' but that is not accurate if it target's TIQ as an 'Advertiser'.  I am available to discuss this and what TIQ is and how it does not directly track nor function as an 'advertiser'.

**Comment by christophertino** [comment] 2020-08-13 14:42
I double checked the [Peter Lowe list](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus) just now and confirmed `tags.tiqcdn.com` is on there.  I do not have control over what goes onto this block list.  We've added it for our users because many of them have requested it, as they like to block as many third-party scripts as possible.

**Comment by chrmod** [comment] 2022-04-25 12:06
Should be fixed by https://github.com/ghostery/ghostery-extension/commit/c5e87fe139a670139cb810f5faadb2aacd5907e2

**Closed by chrmod** 2022-04-25 12:06 UTC
Labels: Type: Ad Blocker
