### ISSUE TITLE
Blocks ajax post requests

### ISSUE THREAD

**Issue by parthibeyond** [ghostery/ghostery-extension#670] opened 2021-01-28 12:54 UTC
Some of our users are using ghostery for ad-blocking were facing trouble using our site. The extension is blocking the ajax requests [Only Post] in our web application. Is this the desired behaviour of Ghostery Addon? Or Is there any workaround for this? 

Should we identify ghostery & ask the user to turn it off?

**Comment by christophertino** [comment] 2021-01-28 14:19
Can you provide the site URL and the URL of the request that is being blocked?

**Comment by parthibeyond** [comment] 2021-01-28 15:59
Sure @christophertino. The details are 

Site URL - https://biblesforamerica.org/place-order/
Request URL - https://ops.bfa.org/api/v1/orders/send_sms_code.json

**Comment by christophertino** [comment] 2021-01-28 16:41
Looks like a false positive for Adobe Analytics. I made the change on our end. It will be out in the next release (about a week or so).  In the meantime, look for Adobe Analytics under Site Analytics in Ghostery and set it to Trust on this Site.

**Comment by parthibeyond** [comment] 2021-01-28 17:24
Will the mentioned change be propagated to all ghostery users without an addon update?

**Comment by christophertino** [comment] 2021-01-28 18:29
It will require an extension update because we are moving to an updated database format (see #616).  This will happen automatically for users with extension auto-updating enabled, which is the majority of our users.

**Comment by parthibeyond** [comment] 2021-02-12 11:30
Hi @christophertino, When is next release planned?

**Comment by christophertino** [comment] 2021-02-16 14:58
We're wrapping up regression tests hopefully today. I'd like to get the build submitted to the stores by Weds or Thurs of this week.

**Closed** 2021-03-05 17:40 UTC
Labels: Type: Tracker Database
