### ISSUE TITLE
Errors during switching ON or OFF Ad-Blocking or other features on iPhone SE

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1260] opened 2023-08-22 14:25 UTC
**Description:**
After switching OFF or ON Ad-Blocking, Anti-Tracking or Never-Consent there is an error in the console and synchronization do not work

**Steps to Reproduce:**
1. Log in.
2. Open Ghostery Settings on the iPhone
3. Open Web Inspector for Ghostery Settings on the MacBook
4. Turn OFF or ON for example Ad-Blocking on the iPhone
5. Check the logs on the MacBook

![Screenshot 2023-08-22 at 16 14 59](https://github.com/ghostery/ghostery-extension/assets/40433708/144cb858-35ee-4441-8bc6-2360b7d37db1)

**Expected Results:**
Synchronization should works.

**Versions:**

	Browser: Safari  
	OS: iOS 15.7.8
	GBE 10.0.2

**Comment by smalluban** [comment] 2023-08-24 13:37
I can confirm the bug on the iOS simulator 15.5. It looks like Safari had a bug, where it applies CORS rules on the extension pages (where it shouldn't). 

@chrmod @philipp-classen I checked, and there is not much we can do on the extension side. The only way to fix the issue is to extend response headers on the account server: `Access-Control-Allow-Origin` with the value `safari-web-extension://*`. As for current iOS, it is possible to make that request by omitting CORS, it should be safe to add it.

**Comment by smalluban** [comment] 2023-08-25 08:01
Adding the above header fixes the CORS issue in Safari 15.x (at least when the local request is replaced in Dev Tools), so the value of the header is fine.

**Comment by smalluban** [comment] 2024-03-28 09:25
I am closing this issue not resolved. Reasons:
1. Currently, ios 15.x is four versions behind the current 18.x
2. This issue can be only resolved on the server side, but I tried hard to make it work on account API server, I coudn't
3. Number of affected users must be very low - no user complained (support, github issue)

**Closed by smalluban** 2024-03-28 09:25 UTC
Labels: v10, Safari
