### ISSUE TITLE
Wordpress 'Select Files' dialog doesn't show up with Ghostery enabled

### ISSUE THREAD

**Issue by joeczucha** [ghostery/ghostery-extension#259] opened 2018-12-03 18:23 UTC
### Description

Wordpress 'Select Files' dialog doesn't show up. After disabling Ghostery, everything works as expected.

### Expected Behavior 

The dialog should appear, allowing you to select a file.

### Actual Behavior 

Nothing - and no errors in JS console.

### Steps to Reproduce

1. Visit Wordpress admin panel
2. Click `Media`
3. Click `Add new`
4. Click `Select Files` 

### Versions

+ Browser: Version 70.0.3538.110 (Official Build) (64-bit)
+ OS: MacOS Mojave 10.14.1 (18B75)

**Comment by christophertino** [comment] 2018-12-10 16:34
@joeczucha I wasn't able to reproduce this on two WordPress sites that I tested with Chrome 71 and Ghostery 8.2.6.  I wonder if this is related to #254 since it also involves a dialog window.

**Comment by joeczucha** [comment] 2018-12-12 11:50
Hi @christophertino 

I've just been playing with this and I've found that there are certainly similarities between the two issues.

I've posted some of my findings on #254 but, in this case:

I have an iMac in my office and a Macbook Pro at home. I'm running Chrome Version 71.0.3578.80 on both and have recently restarted both browsers/machines. To test, I'm running in "incognito mode" with Ghostery (version 8.2.6) as the only active extension on both.

On the iMac - if I visit a Wordpress site and follow the steps above, nothing happens

On the MBP - if I do the same, the file chooser opens correctly

Disabling Ghostery on the iMac causes it to function in the same way as the MBP (i.e. the file chooser opens correctly)

I just tried uninstalling and reinstalling Ghostery but it's made no difference

Let me know if there any logs I can provide from either/both machines to help you get to the bottom of this.

**Comment by christophertino** [comment] 2018-12-17 16:59
@joeczucha thanks very much for this info.  When you have a second, could you please check the Web Console for that page and see if any errors are thrown when clicking 'Select Files'?  

Similarly, we can check for errors in Ghostery by visiting chrome://extensions/, enabling Developer Mode (top right), then where Ghostery is listed, click "background page".  See if any errors are thrown when clicking on one of the blocked links.

**Comment by joeczucha** [comment] 2018-12-18 17:34
Hi @christophertino I've just checked it there and both the web console and background page console are blank.

Just to add, "Pausing" Ghostery makes no difference; it's only when I disable it in Chrome that it starts to work.

**Comment by Anvano** [comment] 2019-01-10 09:57
I have the same issue.
Chrome version  71.0.3578.98  Windows 7 Professional
Ghostery version  8.2.6

Any controls at any sites that opens  "Select Files" dialog does not work when plugin enabled.
Drag & Drop  files works fine.

Web console clear - no messages.

**Comment by jingtra** [comment] 2019-01-10 14:59
Same problem here.

**Comment by LtPatterson** [comment] 2019-01-10 16:09
Request this be merged with #314

**Comment by christophertino** [comment] 2019-01-10 16:45
I can reproduce now in Chrome every time with Ghostery enabled.  I'm not sure what changed but it appears to be much more widespread.  We are working on a fix.

**Comment by philipp-classen** [comment] 2019-01-11 00:07
@christophertino Can you please mark it as a duplicate of #314 

Chrome is rolling back their experiment, which should fix it.

**Comment by christophertino** [comment] 2019-01-11 18:07
Duplicate of #314 

Latest Chrome rollout appears to have fixed the issue.

**Closed by christophertino** 2019-01-11 18:07 UTC
