### ISSUE TITLE
Advertising category is not enabled

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#947] opened 2022-11-28 12:51 UTC
**Description:**
Advertising category is not enabled.

**Steps to Reproduce**
1. Start with a fresh Firefox profile and install the Ghostery extension. 
2. Wait for onboarding tab. Do not click anything on that tab.
3. Firefox will ask to allow Ghostery in private mode. Enable and confirm.
4. Now the tab with the onboarding is closed by Firefox.
5. Ghostery is still disabled. Enable it through the UI (enabled and confirming onboarding).
6. Ghostery is now enabled
7. Check the list of trackers. The list is empty.

https://user-images.githubusercontent.com/40433708/204282095-acbf7dcf-3447-46ec-a516-e51b878ec956.mp4

**Expected Results:**
Advertising category is enabled.

**Version:**
Browser: Firefox 108.0b7
OS: Windows 10 Pro 19044.2006
GBE 8.9.7

**Comment by chrmod** [comment] 2022-12-16 09:31
closing as duplicate of https://github.com/ghostery/ghostery-extension/issues/956

**Closed by chrmod** 2022-12-16 09:31 UTC
Labels: Type: Bug, Firefox
