### ISSUE TITLE
Ghostery cannot be whitelisted on local domains

### ISSUE THREAD

**Issue by dok18** [ghostery/ghostery-extension#623] opened 2020-10-23 11:11 UTC
### Description

I have in my local network domains like: http://hassio:8123. "hassio" is pointing to a server in my local network. I cannot white list them. It is also not possible to add hassio:8123 to white list manually.

### Expected Behavior

White list should accept any host (even without dot in the name) with any valid port.

### Actual Behavior

It add "hassio" to white list (not hassio:8123) and white list does not work

+ Browser: Chromium
+ OS: Ubuntu

**Comment by GoblinLegislator** [comment] 2021-01-13 12:08
I can whitelist any domain including my local apache's localhost and localdiskd. No need to specify port, it works for all ports.
uMatrix would not allow the same. So don't really see what is an issue here. Tested on Chrome, Windows 10.

**Comment by todditron** [comment] 2022-08-26 17:25
Same issue here. I have a local development site running at http://myipi:8888/
The 'trust site' button fail to work (icon always stays blue, never disengages, even after refresh). 
Manually adding the url fails.

I have tried all of these variations, non are considered valid urls
http://myipi:8888/
http://myipi
myipi
myipi:8888

![Results_–ipi](https://user-images.githubusercontent.com/1143370/186959213-2cec826c-5edb-46cc-b411-f1bc2965bdb9.jpg)

Current Chrome & IOS

**Comment by chrmod** [comment] 2022-10-21 08:45
@GRadziejewski can you please confirm if this is still happening. If so, please assign a "Bug" label

**Comment by todditron** [comment] 2022-10-21 18:21
(I just did a quick retest - the behavior is still as I described back in August and as described by the original report -  unable to whitelist local domains)

**Comment by chrmod** [comment] 2022-10-24 08:21
Thank you for the confirmation @todditron !

**Comment by haayman** [comment] 2023-03-27 17:45
same if you have a little longer domain name. I've got http://linux.home/ Doesn't work

**Comment by philipp-classen** [comment] 2023-04-03 12:00
(Reopening, since it was auto-closed.) The fix will be part of the upcoming release.

**Comment by haayman** [comment] 2023-04-27 07:48
some comment: I can now manually add 'linux.home*' to the trusted site (thanks!), but when I'm in linux.home:3000 the button 'trust this site' still doesn't work.

**Comment by philipp-classen** [comment] 2023-04-27 10:55
@haayman Thanks for feedback! We should check that.

**Comment by todditron** [comment] 2023-05-02 20:36
Same issue as @haayman - I can manually add my local sites to trusted sites list, but the 'trust this site' button still does nothing

**Comment by smalluban** [comment] 2024-06-17 08:10
Chrome platform migrated to v10. Feel free to re-open if the issue is still valid.

**Closed by smalluban** 2024-06-17 08:10 UTC
Labels: Bug
