### ISSUE TITLE
Full Screen on Youtube and many other sites is not working

### ISSUE THREAD

**Issue by jupiter14** [ghostery/ghostery-extension#310] opened 2019-01-10 03:11 UTC
### Description
Clicking on Full Screen icon on Youtube and many other video sites is not working. It does not make the video full screen.

### Expected Behavior 

Clicking on the Full Screen icon should enable the video in full screen mode.

### Actual Behavior 

Nothing happens.

### Steps to Reproduce

Enabling the extension causes this problem. If the extension is disabled, the problem goes away.

### Versions
Ghostery for Chrome version 8.2.6

+ Browser:
Chrome  - Version 71.0.3578.98 (Official Build) (64-bit)

+ OS: 
Window 10
+ Node:
+ NPM:

**Comment by JeremyLC** [comment] 2019-01-10 14:48
On YouTube you'll get this in the developer console every time you click the fullscreen button.

`Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.
zr @ base.js:1116
g.h.Gd @ base.js:4908
g.h.bH @ base.js:5907
base.js:1116 Uncaught (in promise) TypeError: fullscreen error
    at zr (base.js:1116)
    at g.BJ.g.h.Gd (base.js:4908)
    at dS.g.h.bH (base.js:5907)
zr @ base.js:1116
g.h.Gd @ base.js:4908
g.h.bH @ base.js:5907`

**Comment by christophertino** [comment] 2019-01-10 16:39
I can reproduce as well.  Looks like one of our content scripts is interfering with the click event.  We're currently looking into it.

**Comment by philipp-classen** [comment] 2019-01-10 19:32
Looks like a duplicate of #314

**Comment by janvernieuwe** [comment] 2019-01-10 21:18
Can confirm this on Win 7 Chrome 71, it's quite annoying.
Pressing F to go fullscreen does seem to work.
Whitelisting the site does not work, only disabling the extension.

**Comment by philipp-classen** [comment] 2019-01-11 00:07
@christophertino Can you please mark it as a duplicate of #314

Chrome is rolling back their experiment, which should fix it.

**Closed** 2019-01-14 18:13 UTC
