### ISSUE TITLE
currentURL is not defined console error

### ISSUE THREAD

**Issue by chrisblakley** [ghostery/ghostery-extension#267] opened 2018-12-09 04:36 UTC
### Description

`currentURL` is not defined in content_script_bundle.js on line 13.

### Expected Behavior 

No console error.

### Actual Behavior 

Console error appears.
![screen shot 2018-12-08 at 11 24 14 pm](https://user-images.githubusercontent.com/6349678/49693431-84d79600-fb40-11e8-85f5-af0485118303.png)

### Steps to Reproduce

I've only noticed this on [my website here](https://gearside.com/nebula/), and it could be something to do with the Service Worker... Unfortunately I cannot get it to consistently occur, but I do know that it occurs on both my work computer and home computer (different computers, but same OS and browser).

When I was developing the service worker this error was happening often, but when only casually viewing the front-end it does not happen as often. If I can expectedly reproduce this I will certainly update this issue.

If I just load the site linked above and open the console and wait, it appears after a while (30-60s). I don't know if scrolling or clicking non-linked areas affect it.

### Versions

+ Browser: Chrome 71.0.3578.80
+ OS: Mac Os 10.14.1

![screen shot 2018-12-08 at 11 36 05 pm](https://user-images.githubusercontent.com/6349678/49693477-0ed42e80-fb42-11e8-80ed-b37c02745d62.png)

**Comment by christophertino** [comment] 2018-12-10 16:02
Looks like this has popped up on stackoverflow too:

https://stackoverflow.com/questions/53527188/new-currenturl-is-not-defined-error-in-google-apps-script-web-apps

**Comment by clt2rdu** [comment] 2018-12-13 17:10
We are also getting this error on all of our websites.  When I turn Ghostery off, the error goes away.  When I turn it back on, the error comes back so I have resorted to keeping Ghostery off until I need to see what tags are firing for QA purposes.

**Comment by philipp-classen** [comment] 2019-01-03 15:34
It has been fixed in the development version. The error message should go away with the next release.

**Comment by iki** [comment] 2019-01-06 13:02
@philipp-classen Thanks for fixing that! It breaks both Ghostery and some sites like Messenger in my Opera.

Disabling Ghostery until the release fixes that. However, it's a strange feeling allowing all trackers in :(

When do you expect the [release](https://github.com/ghostery/ghostery-extension/releases), please?

**Comment by philipp-classen** [comment] 2019-01-06 20:31
@iki Ghostery 8.3 is now in internal testing. From this point on, it is mostly about fixing regressions, but it depends on what issues will still be found.

**Comment by philipp-classen** [comment] 2019-01-16 21:23
@iki Release is live.

**Closed** 2019-01-18 14:35 UTC
