### ISSUE TITLE
Ghostery extension not loading Safari 17.6/Mac OS 12.7.6

### ISSUE THREAD

**Issue by levin-lab** [ghostery/ghostery-extension#2124] opened 2024-12-08 13:19 UTC
2015 MacBook Pro. Safar Version 17.6 (17618.3.11.11.7, 17618). Mac OS 12.7.6.

Updated to most recent version of Ghostery Version 10.4.17 (53). Extension doesn't load. No option to load it.

<img width="512" alt="image" src="https://github.com/user-attachments/assets/4347737b-ea6d-4d75-ad86-51f213a6a243">

<img width="942" alt="image" src="https://github.com/user-attachments/assets/b85c8f80-6909-45f2-89a7-8ca4d24da7eb">

**Comment by seia-soto** [comment] 2024-12-09 01:57
Hi @levin-lab ,

We're sorry for the inconvenience.

It looks like there are a few users experiencing this on macOS version 12.7. Can you share what happens if you restart your mac or reinstall the extension from App Store after the complete removal?

Best

**Comment by levin-lab** [comment] 2024-12-16 15:58
Hi,
I restarted my Mac, then deleted and re-installed Ghostery from the App Store. No luck :-(

Matt


On Dec 8, 2024, at 8:57 PM, HoJeong Go ***@***.******@***.***>> wrote:



Hi @levin-lab<https://github.com/levin-lab> ,

We're sorry for the inconvenience.

It looks like there are a few users experiencing this on macOS version 12.7. Can you share what happens if you restart your mac or reinstall the extension from App Store after the complete removal?

Best

**Comment by Gabriel-Science** [comment] 2024-12-27 11:55
I have the same issue for months, sadly.
![Capture d’écran 2024-12-27 à 12 55 28](https://github.com/user-attachments/assets/9bdfba91-b1e6-4b15-bebf-f315ffc2da01)

**Comment by seia-soto** [comment] 2024-12-28 11:27
Hi @Gabriel-Science ,

First, we're sorry for the inconvenience.

We found that the following methods may resolve the issue on macOS Monterey which is shipped with Safari 14 and has a latest version of 17.

1. We know that restarting apps and device is the first thing we can try, and we assume you already tried it. However, please try after reinstalling the app and restarting the device if you haven't done.
2. Please, make sure that you have a latest version of Safari on macOS Monterey. You can check if there is any Safari update in "Software update" menu of "System Preferences.app".
3. If you're still suffering from the issue, close Safari and other apps then open "Terminal.app". After that, run `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f -R /Applications/Safari.app` and wait for the command to complete (you'll see the line starting with "%" character again). Then restart the device.

It's still difficult to suspect the reason because we don't know exact what triggers the problematic state. However, we're still trying to understand and reproduce the case with testing environment.

I hope you to have a perfect year end, and thank you for using Ghostery.

**Comment by seia-soto** [comment] 2024-12-28 11:32
Hi @levin-lab ,

I know that it has been a while after getting a reply, but I'm letting you know about the possible workaround we've found. If you're still having a same issue, then you can try to do the method 3 from the above message:
> If you're still suffering from the issue, close Safari and other apps then open "Terminal.app". After that, run `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f -R /Applications/Safari.app` and wait for the command to complete (you'll see the line starting with "%" character again). Then restart the device.

Sorry for being late but we still hope your web surfing is privacy cared.

I hope you to have awesome year end, and thank you for reporting your environment which was having an issue.

**Comment by Gabriel-Science** [comment] 2024-12-28 17:14
Using the Terminal ? I like that.
I will test the different solutions rn.
Thanks for the help !

**Comment by Gabriel-Science** [comment] 2024-12-28 19:26
@seia-soto It worked with the Terminal !

**Comment by seia-soto** [comment] 2024-12-28 23:27
Thank you for the confirmation. I'm closing this issue as we know how to fix this now. 👍

**Closed by seia-soto** 2024-12-28 23:27 UTC

**Comment by levin-lab** [comment] 2024-12-29 21:57
I am traveling without my laptop. Will try this fix when I get home next week.

On Dec 29, 2024, at 8:27 AM, HoJeong Go ***@***.***> wrote:

﻿

Thank you for the confirmation. I'm closing this issue as we know how to fix this now. 👍

**Comment by levin-lab** [comment] 2025-01-09 12:15
Hi, this fix worked. Thanks.
