### ISSUE TITLE
Ghostery causing PWA install prompt spam

### ISSUE THREAD

**Issue by dmurph** [ghostery/ghostery-extension#1582] opened 2024-05-07 18:33 UTC
Hello,

Sites that are [promotable and use the beforeinstallprompt](https://web.dev/articles/promote-install) API can spam ghostery users with install prompts. They just have to specify this as their beforeinstallprompt event handler:

```
window.addEventListener('beforeinstallprompt', (e)=>{
  e.prompt();
});
```
Example: https://parkseed.com/, click on any link from their menu bar.

During normal operation, this should simply print the following to the console:
```
Uncaught (in promise) DOMException: Failed to execute 'prompt' on 'BeforeInstallPromptEvent': The prompt() method must be called with a user gesture
    at [https://parkseed.com/Javascript/HomePageJS.bundle.js?v=65:495:7](https://www.google.com/url?q=https://parkseed.com/Javascript/HomePageJS.bundle.js?v%3D65:495:7&sa=D&source=buganizer&usg=AOvVaw14de6MRVAw-FT3r8ppE_Rk)
```

With ghostery installed, it does this, AND somehow the 'prompt()' call [here](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/app_banner/before_install_prompt_event.cc;l=98?q=%22The%20prompt()%20method%20must%20be%20called%20with%20a%20user%20gesture%22&ss=chromium) is activated, meaning that ghostery has somehow caused this event handler to be fired again with the 'user gesture' flag set.

So the simple test case is:

- Install Ghostery
- Visit parkseed.com
- Click on any link from their menu bar

Expected:
- Simple navigation

Actual:
- PWA install prompt shown
- Navigation occurs

As a separate note.... it's pretty concerning that Ghostery is triggering javascript even listener code and pretends to be a user gesture. This user gesture flag is used to prevent malicious API usage that at a minimum spams the user, like the PWA install prompt. Can whatever functionality that needs to do this be redesigned, or at least locked down so it doesn't call any random even listener again? This is pretty scary.

Corresponding chromium issue: https://crbug.com/338254614

Test site: https://motley-petite-friday.glitch.me/

**Comment by dmurph** [comment] 2024-05-07 18:41
Maybe this isn't scary and caused by something else - but it does seem to only repro with ghostery.

**Comment by dmurph** [comment] 2024-05-07 22:04
Seems like a chrome issue actually

**Comment by chrmod** [comment] 2024-05-08 08:45
@dmurph Thank you for your report!

When reproducing I was able to crash Chromium, so something is definitely off. 
Also, Firefox and Safari don't look to be affected (Probably have no support for PWA install prompts at all?)

Was able to identify that it is one of Ghostery core features - the [Never-Consent](https://www.ghostery.com/blog/never-consent-by-ghostery) that triggers the Chromium bug. As you have correctly noticed, this feature emulates user gestures to interact with Consent Managers to opt-out from all tracking on users behalf. So Ghostery the functionality works as expected. 

For your information, this feature is implemented by the [autoconsent](https://github.com/duckduckgo/autoconsent) library. I've notified their authors as more user, beyond Ghostery may be affected.

Will look into this deeper, maybe we can identify a rule that is responsible and implement it differently.

**Comment by dmurph** [comment] 2024-05-08 23:25
I believe this has to do with the beforeinstallprompt catching a 'user gesture' when it really should never catch one. I guess user gestures are kind of 'on for some amount of time' for every js event? I would love to disable this for this specific event handler call, not sure how to do that yet.

**Comment by dmurph** [comment] 2024-05-14 19:31
Circling back here - I don't see an obvious way to prevent user activation detection on a specific event listener. It does seem like having the ghostery extension installed with the autoconsent library causes more events to have the 'user activation' gesture active. This is a dangerous thing to do, and I hope something else can be implemented instead. By doing this you're opening up the user to dangerous stuff - one example is that website can spam permission requests. [Example](https://stackoverflow.com/questions/70007274/what-is-must-be-handling-a-user-gesture-to-show-a-permission-request-errror-m), various dangerous APIs use this to prevent spamming the user and malicious behavior. WebUSB is another, I believe bluetooth as well?

**Comment by dmurph** [comment] 2024-05-15 23:03
More things that can happen:
- audio autoplay is blocked until user activation. This allows sites to auto-play music or videos with audio.
- fullscreen is blocked on user activation. This allows sites to make themselves fullscreen.

See more APIs that reference sticky activation [here](https://dontcallmedom.github.io/webdex/s.html#Sticky%20activation%40%40html%25%25dfn) and user activation [here](https://dontcallmedom.github.io/webdex/u.html#user%20activation%40%40html%25%25dfn). That means something in that spec is guarded on user activation. there may be more terms, I'm not sure (hard to look up list of all things that use user activation).

**Comment by philipp-classen** [comment] 2024-05-17 09:45
Needs more testing, but it looks like it is only an issue on Ghostery 8 (on Chrome). But I think it is not the autoconsent library, and also the upcoming Ghostery 10 version seems to be unaffected. (For details, see https://github.com/duckduckgo/autoconsent/issues/443#issuecomment-2117152334)

To simplify testing, we can use the test site that @dmurph has created:

1. Go to https://motley-petite-friday.glitch.me/
2. Click on "Click me"

With Ghostery 8 (on Chrome), I get the "install app" popup. However, with Ghostery 10 (built locally following the steps in https://github.com/ghostery/ghostery-extension/tree/main/extension-manifest-v3), I cannot reproduce any longer.

**Comment by dmurph** [comment] 2024-05-17 16:53
Thanks so much for the debugging!

**Comment by philipp-classen** [comment] 2024-05-21 13:09
Removing the "edge" label, since Ghostery 10 has been released on Edge.

**Comment by htalat** [comment] 2024-05-21 18:19
@philipp-classen I am able to repro in Edge Canary 127.0.2599.0  with Ghostery 10.3.2 though this time the spamming has stopped. The prompt shows up once ~5 clicks with @dmurph's example site https://motley-petite-friday.glitch.me/

**Comment by dmurph** [comment] 2024-05-21 19:03
That behavior is unfortunately the chromium bug, so currently that is WAI according to spec

**Comment by philipp-classen** [comment] 2024-06-06 10:58
Ghostery 10 has just been released on Chrome. With that it should be fixed on all platforms. (Firefox is still on Ghostery 8, but it is not affected.)

**Comment by smalluban** [comment] 2024-06-12 13:23
@dmurph Feel free to re-open if the issue still exists in v10.x version of the extension.

**Closed by smalluban** 2024-06-12 13:23 UTC
Labels: Bug, Chrome, v8
