### ISSUE TITLE
Ghostery does not keep me logged-in

### ISSUE THREAD

**Issue by WFransL** [ghostery/ghostery-extension#43] opened 2018-04-21 05:42 UTC
Ghostery does not keep me logged-in

I would expect that once logged in to Ghostery on a PC That Ghostery stays logged-in between sessions, Is is not what happens. Every now and then I have to log-in again.

1. Start PC
2. Open Browser
3. Check if Ghostery is logged-in

+ Chrome 66.0.3359.117
+ WIN10
+ Ghostery 8.1.2

**Comment by Aziz-Ghostery** [comment] 2018-04-25 21:32
Hi There, 
We've had dealt with this issue awhile ago, and we frankly thought it was fixed.
We'd appreciate it if you could help us troubleshoot this issue by answering the following questions:
When you are not using your machine, do you choose to:
Log off: 
Clock:
Sleep:
Shutdown:
How long do you normally leave your machine in the above state?

Chrome Settings:

Privacy and security ==> Content settings ==> Cookies 
Allow site to Save & read cookie data (On/Off):
Keep local data only until you quit your browser (On/Off):
Block third-party cookies (On/Off):

Privacy and security ==> Content settings ==> JavaScript

Allowed (On/Off): 

System ==> Background Apps

Continue running background apps when Google Chrome is closed (On/Off):

Regards,
Aziz

**Comment by WFransL** [comment] 2018-04-26 04:34
See my responses 

The issue of being logged out is not limited to Chrome. Also in MS-Edge Ghostery is logged-out.

When you are not using your machine, do you choose to:

One system is shutdown- ed when I do not used this system and the system is used daily
Another system is always on (even does not ‘sleep’) and used daily

Chrome Settings:
Allow site to Save & read cookie data (On/Off): On
Keep local data only until you quit your browser (On/Off): Off
Block third-party cookies (On/Off): Off

Privacy and security ==> Content settings ==> JavaScript: Allowed (On/Off): On

Continue running background apps when Google Chrome is closed (On/Off): Off

**Comment by markofstrathclyde** [comment] 2018-05-08 15:05
(Firstly : great extension) 

But... me too, any thoughts much appreciated.

Ta

Mark

---

Windows 10 build 1709 64-bit Intel-i5  Chrome 66.0.3359.139

When you are not using your machine, do you choose to:
Normally sleep or switch accounts with hibernation happening if left alone for 8 hours +

Chrome Settings:

Privacy and security ==> Content settings ==> Cookies
Allow site to Save & read cookie data (On/Off): on
Keep local data only until you quit your browser (On/Off): off [is that the problem??]
Block third-party cookies (On/Off): off

Privacy and security ==> Content settings ==> JavaScript

Allowed (On/Off): on

System ==> Background Apps

Continue running background apps when Google Chrome is closed (On/Off): off

**Comment by konqui** [comment] 2018-05-31 12:52
same here i also always get logged out

**Comment by computeronix** [comment] 2018-07-02 19:43
+1, Edge and Chrome keeps logging me out over time.  For a while I stay logged in, then randomly get logged off.  My other extensions I use keep me logged in all the time.

Windows 10 (every build I have used is affected).

**Comment by oduis** [comment] 2018-07-03 04:42
Same here. I have several machines, and I thought it saw a correlation there, when I log in to another machine it logs me off on the initial machine.
Could it be that the user data is synced across devices?

**Comment by webgroupWest** [comment] 2018-07-03 13:29
Definitely "me, too." I recall the "fix" some time back, but it only remained fixed for a few weeks. It's been logging me out constantly, ever since.

Doesn't seem to matter how I log-out of Windows (usually hibernate, or shut down), and my Chrome settings are as you specify above.

Happens all the time for me on Windows, and my Chromebooks.

FWIW, other extensions that maintain my sign-in (such as Trello, Evernote, etc.) do not have this problem. It definitely seems specific to the ghostery implementation.

**Comment by mgrigni** [comment] 2018-07-05 12:38
I see this also, is the "do not track" setting relevant?

**Comment by christophertino** [comment] 2018-07-06 20:19
Hey guys, we hear you on the log-out issue.  We have a new v2 API for our user authentication system that @trickpattyFH20 is currently integrating on the [feature/api-v2-auth](https://github.com/ghostery/ghostery-extension/tree/feature/api-v2-auth) branch. It kills the old refresh token logic that caused all this headache.  We're scheduling this for our 8.2.1 release hopefully next week.

**Comment by christophertino** [comment] 2018-08-10 15:59
We released v8.2.3 earlier in the week which should resolve the logout issue.  Please give it a test and let us know if you're still getting logged out.

One note: If you have your browser set to clear cookies on close you will be logged out of Ghostery.  In Chrome, the setting "Keep local data only until you quit your browser" should be off. In Firefox, you should have Cookies and Site Data > Keep until they expire.

**Comment by altae7** [comment] 2018-08-12 02:11
The issue is fixed? On the contrary, login is completely broken for me (Arch Linux, Firefox). I cannot even login anymore. If I try it tells my login attempt was successful but as soon as I close the Ghostery pop-up and re-open it I'm logged out again.

**Comment by christophertino** [comment] 2018-08-14 13:58
Thanks for the heads up @altae7.  It looks like the Firefox implementation of `chrome.cookies.onChanged` is a little wonky.  It was also causing problems on Edge.  #158 should be the answer.

**Comment by altae7** [comment] 2018-08-14 20:47
Thanks. This means we have to wait for a new version to come out, right?

**Comment by trickpattyFH20** [comment] 2018-08-15 13:59
@altae7 yes a fix for this will be out with the next release

**Comment by christophertino** [comment] 2018-08-21 21:05
We found a few more edge-cases contributing to this issue that have now been patched.  We're testing the [release build](https://github.com/ghostery/ghostery-extension/releases/tag/v8.2.4) now.

**Comment by christophertino** [comment] 2018-08-23 13:35
@altae7 @mcicconi Ghostery v8.2.4 is now live.  Please let us know if you can now remain signed in.

**Comment by WFransL** [comment] 2018-08-23 14:45
Nope, closing EDGE logs me out each and every time. 

I have unchecked to delete cookies upon closing in EDGE.

CCleaner leaves EDGE cookies untouched

 

Chrome works ‘as expected’ and I stay ‘logged-in’.

 

Frans Lichtenauer

 

P: +31 487540980

F: +31 878756623

M: +31 653171630

P Please consider the environment before printing this e-mail

**Comment by altae7** [comment] 2018-08-23 15:38
Negative, still the same. I cannot login at all.

**Comment by Aziz-Ghostery** [comment] 2018-08-24 14:32
@altae7 We are working a logout issue for Edge Browser, However V 8.2.4 has the fix for Chrome andFF. Would you please restart your Chrome browser, make sure you are on V 8.2.4 and try sign in again.
Please let us know the outcome, Thanks.

**Comment by altae7** [comment] 2018-08-24 15:31
I don't use chrome, I use Firefox. And login does not work despite the fact that Ghostery 8.2.4 is installed and I've restarted the computer several times in the meantime. It's simply broken.

**Comment by Aziz-Ghostery** [comment] 2018-08-24 19:36
@altae7  This might be due to a corrupted cookies.sqlite file in Firefox's profile folder. 
In order to fix this, just rename or remove cookie.sqlite while Firefox is not running.
Open a terminal of choice and type the following:
$ rm -f ~/.mozilla/firefox/<profile id>.default/cookies.sqlite
The profile id is a random 8 character string.
Restart Firefox and see if it solved the problem.
If the issue persists try creating a new FF profile reinstall Ghostery in that profile and see if the issue is solved.

**Comment by Lokumskaster** [comment] 2018-08-26 19:35
Just installed Windows 10 today. Installed Chrome including Ghostery (8.2.4). I have had to log on three times today already.

**Comment by Storm-Engineer** [comment] 2018-09-15 01:30
I just noticed this as well. I can't stay logged in either.

@Aziz-Ghostery I tried deleting my cookies.sqlite but it did not fix it.

Arch Linux
Firefox 62.0
Ghostery 8.2.4

**Comment by Storm-Engineer** [comment] 2018-09-21 16:32
@christophertino I already had an allow exception for the whole ghostery.com domain.

The only cookie getting created is analytics.ghostery.com

**Comment by altae7** [comment] 2018-09-22 22:55
Ok, thanks for the reply. It's the first party isolation then. Since I'm not willing to disable it I'll live with not being able to login.

**Comment by Storm-Engineer** [comment] 2018-09-23 10:02
@christophertino I did some further testing. Apparently FF's handling of "3rd party" cookies is the issue.

I had 3rd party cookies set to "never allow", and using Allow exceptions for sites I use. This worked in the past. Now however, apparently it doesn't anymore.

Changing 3rd party cookies to "always" fixed the login issue and changing it back to "never" broke it again. This sounds like a Firefox bug to me because I'm pretty sure Allow exceptions should still work with 3rd party.

**Comment by christophertino** [comment] 2018-09-25 08:50
@Storm-Engineer Can you try setting an Allow exception for `https://consumerapi.ghostery.com` ?

I was able to force the logout with third party cookies set to Never, but adding an exception for the above domain seems to clear it up. Let me know.

**Comment by Storm-Engineer** [comment] 2018-09-26 15:07
@christophertino Yes, setting that exception soled it indeed.

But I already had an Allow for the main "ghostery.com" domain, and that should have did the trick already without explicitly setting the subdomain. Plus, other sites have malfunctioned lately as well (eg. YouTube kept forgetting the Dark theme and Autoplay settings) until I set it from Never to Visited.

So I still think Firefox started handling this differently, either intentionally or because of a bug.

**Comment by trickpattyFH20** [comment] 2018-10-09 20:45
For anyone unable to login from the extension panel on Ubuntu:
It looks like there is a bug with the Linux package ibus that closes any extensions in FF as soon as a `type=password` field is focused [ibus#2002](https://github.com/ibus/ibus/issues/2002#issuecomment-396711051)

Other extensions are experiencing the same problem, and unfortunately there isn't much we can do to workaround it. [bitwarden#580](https://github.com/bitwarden/browser/issues/580)

If this is the case, you can try logging in from the Ghostery website https://signon.ghostery.com
The authentication from there should carry over to the extension.

**Comment by rakoczy** [comment] 2018-10-28 21:37
> 
> 
> @Storm-Engineer Can you try setting an Allow exception for `https://consumerapi.ghostery.com` ?
> 

How to do it in FF63?

**Comment by christophertino** [comment] 2018-10-29 15:31
@rakoczy It's under Preferences > Privacy & Security > Cookies & Site Data > Exceptions

**Comment by salieri** [comment] 2020-01-31 16:54
This issue remains with Ghostery 8.4.6 on Google Chrome 80.0.3987.78. You log in to Ghostery, forget it for a few days or a week, and when you check back you are logged out.

**Comment by christophertino** [comment] 2020-03-02 14:55
Are you clearing cookies on browser close? That would cause a logout. Another thing to consider is that the refresh token expires after 7 days. So if you don't open your browser for a week you would get logged out of Ghostery.

**Comment by salieri** [comment] 2020-03-11 14:47
@christophertino I don't think either one of those accurately describes my case. I certainly don't clear cookies on browser close, and I think this issue occurs often enough that the second one is not the case either, but it's hard to be sure. I'll check that.

On that note, though: If Ghostery silently discards an expired cookie and doesn't inform the user that their session is no longer valid, then the UX is very confusing. How would the user ever know when to log back in?

**Comment by tankmann** [comment] 2020-03-14 14:44
I have exact the same issue... I only recognize it when I get an offer showing and then I remember or I'm logged out again. Using computer / browser every day, don't delete cookies often... Only thing I have is two location profiles on my mac I switch (office and home), but that can't be the reason. It's actually really annoying, I'm paying and then have to re-login all the time.

**Comment by christophertino** [comment] 2020-04-11 18:21
@tankmann Are you on Chrome as well?

**Comment by tankmann** [comment] 2020-04-12 07:14
> @tankmann Are you on Chrome as well?

Yes I'm on Chrome as well.
OSX 10.15.4 (19E287)
MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by bramdejager** [comment] 2020-04-20 09:09
Same issue here, I'm running Ghostery for Edge version 8.4.8 on Windows 10. This is the new Edge browser from Microsoft on Chromium.

**Comment by tankmann** [comment] 2020-05-06 11:53
Ping Pong?

**Comment by tankmann** [comment] 2020-06-30 18:18
I've cancelled my subscription now... Had enough of being logged out all the time plus no reaction here.
Bye.

**Comment by mojorisinagain** [comment] 2020-12-14 20:33
Running Ghostery version 8.5.4, in Chrome version 87.0.4280.88 (64-bit), on Windows 10 Pro.  Started seeing this automatic log out "re-released feature" in mid-to-late November, 2020.  Annoying

**Comment by etuttle** [comment] 2021-04-26 04:06
I run Ghostery on [ungoogled-chromium-macos](https://github.com/ungoogled-software/ungoogled-chromium-macos) which is a combo I was so excited about!  Until I noticed this dropped authentication issue.  In my case, I've never seen login stick across a browser reboot.  If it does work at all, it is for a very short time.  And I certainly have other extensions that manage to persist their auth.

I will see what I can figure out about 3rd party cookies, exceptions for `https://consumerapi.ghostery.com` and the like.  Meanwhile, I would suggest to Ghostery: after so many years of this problem, could there be a way to detect that it is happening and warn the user?  I would prefer to be alerted about that my session was lost.  Link to a troubleshooting doc?  I (like everyone else here, I bet) had to slowly notice this was happening, get frustrated about it, in my case I emailed support and didn't hear back.  Then I finally find this thread.  Not a positive experience.

Tackling this head-on may not help your bottom line, but it's the user centric thing to do.

**Comment by kheaactua** [comment] 2021-09-19 10:53
Just want to add that I've been running Ghostery for years on multiple browsers (Chrome & Firefox) across multiple computers (Linux and Windows), and it logs me out on everyone.  It's so consistent that I just thought that that was the expected behaviour

**Comment by MichaelKing1832** [comment] 2022-07-10 15:06
This extension is essentially unusable at this point. Running FF 102.0.1 (64-bit) on WIn10 21H2 (build 19044.1806).
Ghostery is logged out on browser launch. Disappointing, but it gets worse. After logging in, any refresh or switching to another tab or going to another URL (i.e. clicking on a link), Ghostery reverts back to its  logged out state.

It used to stay logged in, and for a while (a year or so ago?) it actually stayed logged in across browsers. I am checking other extensions to see if they might be blocking Ghostery. The DuckDuckGo Privacy Essentials extension doesn't seem to have whitelisted the Ghostery.com domain, so I've added it to the exception list. Ghostery will still not stay logged in for more than viewing that one page, forcing a login after every page, tab switch, or even a reload of the same page.

Unacceptable. This extension is non-functional at this point.

**Comment by chrmod** [comment] 2022-07-11 08:08
@MichaelKing1832 thank you for your report. We are about to release https://github.com/ghostery/ghostery-extension/pull/808 which should fix all login problems on Firefox. This release will be called `8.7.6`. We would appreciate if you could let us know if the fixed worked for you.

**Comment by chrmod** [comment] 2022-07-12 12:50
Ghostery `8.7.6` is ready for download from Firefox AMO https://addons.mozilla.org/en-US/firefox/addon/ghostery/?utm_campaign=samesite 
Please let us know if it fixed your problems with not being able to log in. I will keep the issue opened and pinned for a while longer to be sure we got it right this time.

**Comment by MichaelKing1832** [comment] 2022-07-16 15:09
Confirm 8.7.6 is persisting login across tabs and browser restarts with FF 102.0.1 (64-bit) on WIn10 21H2 (build 19044.1826).
Thank you to @chrmod and the rest of the devs for looking into it and being able to resolve it so quickly!
This is especially timely with the recent changes to Chrome and extension API changes for adblockers driving folks to switch to Firefox.

**Comment by MichaelKing1832** [comment] 2022-07-16 15:25
ProTip for users with FF and password managers (e.g. BitWarden): Open Firefox to the Ghostery.com site and login to the website. You will automatically also be logged into the extension.

This is useful because when you are entering login credentials within the Ghostery extension, you are not able to access the other extensions, like BitWarden, to look up and copy/paste the credentials from that extension into Ghostery extension.

**Comment by MichaelKing1832** [comment] 2022-08-28 17:54
@chrmod The issue has returned, but not quite so severely. (:cry)

Now, the login to the Ghostery extension is not persisted across browser restarts/launches. The trick with loggin in to the website (ghostery.com) in order to use a password manager extension still works in that the extension is also logged in.

This behavior is occurring with 8.7.6 and FF 104.0 (64-bit) on Win10x64 21H2 (19044.1889).

**Comment by chrmod** [comment] 2022-08-30 16:09
@GRadziejewski can you please try to reproduce this problem?

**Comment by chrmod** [comment] 2022-08-30 16:09
@MichaelKing1832 thank you reporting those issues, you help is much appreciated. We will do our best to fix it finally.

**Comment by MichaelKing1832** [comment] 2022-09-20 22:44
Noticed something odd. Launched FF (v105.0)+Ghostery v8.7.6+DuckDuckGo v2022.8.25. Disabled FF Enhanced Tracking Protection for ghostery.com. Loaded ghostery sign-in page, signon.ghostery.com/en in FF inspection mode. It looks like the ghostery extension _is blocking itself_ from loading https://consent.ghostery.com/v1.js that gets loaded from the Ghostery login page.

**Comment by MichaelKing1832** [comment] 2022-09-20 22:56
After a successful login, Firefox is reporting this silent failure:

> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:71:798183

**Comment by MichaelKing1832** [comment] 2022-09-20 23:14
Lastly, after the successful login to the extension (via logging into the ghostery.com website), Firefox _seems_ to be retaining the session state between browser launches. I'm going to try re-enabling the different privacy blockers one at a time to see if there is one culprit or it is possibly some combination of them. From a user perspective, it just sucks to have competing "blockers" interfering with each other, and the reality is that none of them are perfect, so the natural thought is to use more than one to benefit from each of their strengths. Unfortunately, when any one of them is too aggressive (or fails to account for the reality that sometimes people use some other vendor's products!) it's a hot mess trying to figure out where the problem is even with deep technical abilities. The average user is understandably left frustrated. So, please, ghostery, reach out to your "competitors" to make sure you're all not pissing in each other's cheerios and work together with FF native "Enhanced Tracking Protections" and DuckDuckGo's Site Privacy Protections. They each have good reasons to exist in our browsers.

**Comment by MichaelKing1832** [comment] 2022-09-20 23:34
Re-enabled Firefox Enhanced Tracking Protection for www.ghostery.com and login.ghostery.com and account.ghostery.com.
Since I never see the other web pages being loaded from analytics.ghostery.com or consent.ghostery.com, there is no ability to try turning them back on (or to turn them off in the first place, pre-emptively). I'll dig into the settings to try to isolate the FF protections and disable them entirely in order to eliminate Firefox from breaking the session retention.

Next up, turning DuckDuckGo protections back on and re-testing for session persistence. Again, since the user never sees they are accessing analytics.ghostery.com or consent.ghostery.com, there is no ability for the user to manage turning them on or off, even pre-emptively.

**Comment by philipp-classen** [comment] 2022-11-16 14:43
Ghostery 8.9.5 has been released now, which includes some fixes regarding the login handling.

**Comment by chrmod** [comment] 2022-12-10 19:28
Since Ghostery 8.9.x is now rolled out to all platforms, we do really hope this issue is finally solved.

@MichaelKing1832 is possible, can you please verify if all works fine for you with latest version?

I'm closing the issue for now.

**Closed by chrmod** 2022-12-10 19:28 UTC
Labels: Type: Bug

**Comment by MichaelKing1832** [comment] 2022-12-18 17:28
Apologies for being away. I'll clear my browser settings, cookies and extensions to re-test.

Also, I read somewhere that in FF, if there are multiple extensions handling events that conflict, whatever the last extension installed was wins control of the event and the others don't get to process it.

Ugh. That's something that will be a problem for lots of users with FF built-in cookie/tracker privacy features, ad and tracker blockers (e.g. Ghostery), privacy extensions (e.g. Duck Duck Go), and popular AV products (e.g. Avast, AVG, BitDefender, ESET, IOBit, Kaspersky, McAfee, etc) that all have browser URL and DOM inspection interceptors.

That's gonna suck for users and of course, none of these products or companies are interested in sharing users as they all consider their walled garden of extensions and products to be complete and uninterested in supporting cohabitation with "competitor" extensions. Just ugh for everyone.

With any luck, we'll just get an arms race by the extension developers to detect when their extension isn't first, and trigger something to re-insert themselves in the top spot. And we sit back and watch the browser flail itself to death with extension fighting. Sigh.

Anyway, I'll post my results of testing to try and figure out these nuances that regular users of Ghostery (and the other extensions) will no doubt encounter.
