### ISSUE TITLE
iframe not loading for certain url's

### ISSUE THREAD

**Issue by FrankOnGit** [ghostery/ghostery-extension#186] opened 2018-09-11 09:20 UTC
### Description

iframes do not load for certain url's

### Expected Behavior 

iframes should all load normally when all trackers are enabled

### Actual Behavior 

only when Ghostery is set to pause, all iframes are loaded. If Ghostery is active, the public gmail calenar of alxfyv@gmail.com will not load. The youtube video loads correctly.

### Steps to Reproduce

1. go to https://tiddlywiki.com/
2. click to + to create a new tiddler (tiddlers can contain text notes, pictures, iframes, etc.)
3. add the following code to this new tiddler:
<iframe width="560" height="315" src="https://www.youtube.com/embed/1g66s7UbyuU"></iframe>

<iframe width="560" height="315" src="https://calendar.google.com/calendar/embed?alxfyv%40gmail.com"></iframe>

4. confirm changes to this tiddler (✔) to see the result. 

### Versions

+ Browser: Firefox 62.0
+ OS: Win7 Enterprise SP1
+ Node:
+ NPM:

**Comment by sammacbeth** [comment] 2018-09-13 08:31
Hi @FrankOnGit, thanks for reporting.

I was able to reproduce this. I see the following error in the browser console:
```
Load denied by X-Frame-Options: https://accounts.google.com/ServiceLogin?service=cl&passive=1209600&osid=1&continue=https://calendar.google.com/calendar/embed?alxfyv@gmail.com&followup=https://calendar.google.com/calendar/embed?alxfyv@gmail.com&scc=1 does not permit framing.
```

It seems that the calendar is not public, as the embed redirects to a google sign-on page. The error happens because Google does not permit their login to be embedded in an iframe. The root cause is that the Ghostery anti-tracking will block the cookies for the iframes, in this case preventing Youtube and Google tracking your visit to the top-level page. You can allow the third-party cookies to be sent for the iframes if you choose 'Trust site' in Ghostery.

**Comment by FrankOnGit** [comment] 2018-09-13 12:11
Hello there
Thank you for your support. Unfortunately I was not able to change my Ghostery settings for trusted websites so I could load my iframes correctly.
Please find a screenshot of my settings as attached image: SettingsNotSuccessful.png
I have found a public calender for you to test using the follwoing code in Tiddlywiki:
<iframe width="550" height="430" src="https://calendar.google.com/calendar/embed?src=g4v6s06cp8tb4cp6up36lmu43g%40group.calendar.google.com&ctz=Europe%2FZurich" style="border: 0" frameborder="0" scrolling="no"></iframe>
Kind regards,
Frank.
----Ursprüngliche Nachricht----
Von : notifications@github.com
Datum : 13/09/2018 - 10:31 (GMT)
An : ghostery-extension@noreply.github.com
Cc : f_huerlimann@bluewin.ch, mention@noreply.github.com
Betreff : Re: [ghostery/ghostery-extension] iframe not loading for certain url's (#186)
Hi @FrankOnGit, thanks for reporting.
I was able to reproduce this. I see the following error in the browser console:
Load denied by X-Frame-Options: https://accounts.google.com/ServiceLogin?service=cl&passive=1209600&osid=1&continue=https://calendar.google.com/calendar/embed?alxfyv@gmail.com&followup=https://calendar.google.com/calendar/embed?alxfyv@gmail.com&scc=1 does not permit framing.
It seems that the calendar is not public, as the embed redirects to a google sign-on page. The error happens because Google does not permit their login to be embedded in an iframe. The root cause is that the Ghostery anti-tracking will block the cookies for the iframes, in this case preventing Youtube and Google tracking your visit to the top-level page. You can allow the third-party cookies to be sent for the iframes if you choose 'Trust site' in Ghostery.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ghostery/ghostery-extension","title":"ghostery/ghostery-extension","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ghostery/ghostery-extension"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sammacbeth in #186: Hi @FrankOnGit, thanks for reporting.\r\n\r\nI was able to reproduce this. I see the following error in the browser console:\r\n```\r\nLoad denied by X-Frame-Options: https://accounts.google.com/ServiceLogin?service=cl\u0026passive=1209600\u0026osid=1\u0026continue=https://calendar.google.com/calendar/embed?alxfyv@gmail.com\u0026followup=https://calendar.google.com/calendar/embed?alxfyv@gmail.com\u0026scc=1 does not permit framing.\r\n```\r\n\r\nIt seems that the calendar is not public, as the embed redirects to a google sign-on page. The error happens because Google does not permit their login to be embedded in an iframe. The root cause is that the Ghostery anti-tracking will block the cookies for the iframes, in this case preventing Youtube and Google tracking your visit to the top-level page. You can allow the third-party cookies to be sent for the iframes if you choose 'Trust site' in Ghostery."}],"action":{"name":"View Issue","url":"https://github.com/ghostery/ghostery-extension/issues/186#issuecomment-420927513"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ghostery/ghostery-extension/issues/186#issuecomment-420927513",
"url": "https://github.com/ghostery/ghostery-extension/issues/186#issuecomment-420927513",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ghostery/ghostery-extension] iframe not loading for certain url's (#186)",
"sections": [
{
"text": "",
"activityTitle": "**Sam Macbeth**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@sammacbeth",
"facts": [
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ghostery/ghostery-extension\",\n\"issueId\": 186,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ghostery/ghostery-extension\",\n\"issueId\": 186\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ghostery/ghostery-extension/issues/186#issuecomment-420927513"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 378251928\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by sammacbeth** [comment] 2018-09-17 11:48
I've just checked this again, and this is fixed in the latest beta version. This should fix your issue once the next version is released.

**Comment by FrankOnGit** [comment] 2018-09-17 14:33
Do you have an account for donations ?
Thank you so much and have a nice day!
Kind Regards,
Frank.
----Ursprüngliche Nachricht----
Von : notifications@github.com
Datum : 17/09/2018 - 13:48 (GMT)
An : ghostery-extension@noreply.github.com
Cc : f_huerlimann@bluewin.ch, mention@noreply.github.com
Betreff : Re: [ghostery/ghostery-extension] iframe not loading for certain url's (#186)
I've just checked this again, and this is fixed in the latest beta version. This should fix your issue once the next version is released.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ghostery/ghostery-extension","title":"ghostery/ghostery-extension","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ghostery/ghostery-extension"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sammacbeth in #186: I've just checked this again, and this is fixed in the latest beta version. This should fix your issue once the next version is released. "}],"action":{"name":"View Issue","url":"https://github.com/ghostery/ghostery-extension/issues/186#issuecomment-421982178"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ghostery/ghostery-extension/issues/186#issuecomment-421982178",
"url": "https://github.com/ghostery/ghostery-extension/issues/186#issuecomment-421982178",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ghostery/ghostery-extension] iframe not loading for certain url's (#186)",
"sections": [
{
"text": "",
"activityTitle": "**Sam Macbeth**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@sammacbeth",
"facts": [
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ghostery/ghostery-extension\",\n\"issueId\": 186,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ghostery/ghostery-extension\",\n\"issueId\": 186\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ghostery/ghostery-extension/issues/186#issuecomment-421982178"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 378251928\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by StephanKl** [comment] 2018-10-30 09:41
@sammacbeth I have the same problem - do you already know (and can share) the release date for the next version of the Ghostery Chrome Extension? Thank you

**Comment by christophertino** [comment] 2018-10-30 17:02
@StephanKl we're currently regressing tickets for v8.3, scheduled for release the week after next (November 12).

**Comment by christophertino** [comment] 2018-11-27 18:12
Fixed in v8.2.5

**Comment by FrankOnGit** [comment] 2019-01-09 08:43
f

**Comment by FrankOnGit** [comment] 2020-11-04 08:59
https://support.apple.com/de-ch/guide/tv/atvb50fb1c50/tvos

**Comment by FrankOnGit** [comment] 2022-05-20 12:04
https://www.ebay.ch/itm/bremermann-Einkaufstrolley-BRINKUM-Handwagen-Einkaufswagen-rot-/162718380425

**Comment by chrmod** [comment] 2022-05-23 08:29
reopening the issue for further investigation

**Comment by smalluban** [comment] 2024-06-18 09:52
Feel free to re-open if the issue is still valid. The only platform that is still on the v8 version is Firefox.

**Closed by smalluban** 2024-06-18 09:52 UTC
Labels: Bug
