### ISSUE TITLE
Trust site does not work

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#1719] opened 2024-07-04 16:15 UTC
Affected website: https://www.llcooljams.com/

**Comment by philipp-classen** [comment] 2024-07-04 16:21
Could be a duplicate of https://github.com/ghostery/ghostery-extension/issues/1690

With the master version (plus https://github.com/ghostery/ghostery-extension/pull/1713), it works for me.

**Comment by philipp-classen** [comment] 2024-07-04 16:31
Confirmed. Closing it as a duplicate of https://github.com/ghostery/ghostery-extension/issues/1690

**Closed by philipp-classen** 2024-07-04 16:31 UTC
Labels: Bug
